### ISSUE TITLE
Verification Statements: Parse PDF contents into more usable format

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/cas-reporting#102]
From Dec. 2023 internal staff research. Have a way to parse PDF information from report into another, more usable format. 
Work with Business Area to determine what format we should use in our new system for verification statements. 
Could it be web forms instead of PDFs? Add the feature of e-signatures to prevent scanning? Use a fillable PDF? 
Note: we do have a word template for this - but they don't always use it correctly. 
Confirm: what problem is this trying to solve? 
See ticket #6 for related work. 

*This could be a huge component of work and likely not possible for the MVP.

**Comment by patriciarussellCAS** [comment]
If I'm understanding this one correctly, it's referring to the PDF format of the verification statements that currently get uploaded through SWRS. We are unable to extract information from them so staff have to go through each one and cut/paste to excel/word to use! 
Flag for potential MVP feature.

**Comment by NicoleGovvy** [comment]
@patriciarussellCAS - exactly. This ties in with including verification done within the system so something to explore further.

**Comment by patriciarussellCAS** [comment]
Added Attention to business area tag so we can confirm what is required for verification, what does the statement look like, how big are these files? To flag for Munish to understand storage capacity for uploads.

**Comment by NicoleGovvy** [comment]
Would be helpful to actually see a statement.

**Comment by rdromey** [comment]
Closed as not technically possible. Can't parse PDFs accurately, technology does not yet exist for this.
