### ISSUE TITLE
Temporary landing page

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-reporting#109]
#### Description:

A landing page for the registration app, with an empty main frame, and login buttons for testing.
This page is only temporary and for development purposes only. The reporting app will be accessible only for logged in users, using the registration app's landing page.

#### Acceptance Criteria:

Given I am a user
When I land on the regporting app's url and I am not logged in
Then I can see a temporary page with 2 buttons: IDIR login and BCeID login

#### Development Checklist:

- [ ] Very minimal styling
- [ ] 2 buttons for login
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
Because login and access will be done from the registration app, this doesn't need to contain any real styling - we just need to go with low effort

**Comment by pbastia** [comment]
@mikevespi where is this at? I'm thinking we won't need it with the new strategy, or do you think 2 landing pages could be what we want?

**Comment by mikevespi** [comment]
I have a PR up in the reporting app that was just going to serve as a temporary landing for us to have a "Login" button. Now that we've moved repos, whether we need this will depend on our local development process. I think that if we don't want to spin up registration in order to be able to log in and work on reporting, it might still be nice to have in there, but as far as a real page that will get to prod, I agree we don't need a reporting specific landing page, they'll share one.

**Comment by pbastia** [comment]
I think this could be pulled back in the backlog - most of the work is done and can be ported over our separate frontend in the monorepo. Thoughts?

**Comment by rdromey** [comment]
Moving to a monorepo structure so no longer needed.
