### ISSUE TITLE
Plan reporting validation with external users

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/cas-reporting#119]
Post-user story mapping session, we'd like to validate our assumptions about how the operators would like to enter information into BCIERS.

We would like to validate our user roles, user stories, features needed for external users for reporting.

- [x] Confirm we are able to do external research with BA director
- [x] Plan scope of work (goals, questions, format, attendees etc.)
- [x] ID operators/individuals we'd like to speak with
- [x] Book user sessions
- [x] Have dry-run session
- [x] Create consent form in CHEFS

**Comment by zoeyli-46** [comment]
Outputs: 
Validate user roles in external operator during reporting
Validate the user stories, feature and functionalities required for the external operators during reporting

**Comment by NicoleGovvy** [comment]
Have sent feelers out.
