### ISSUE TITLE
Review & Modify User Profiles for Reporting

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-reporting#12]
For Reporting, we'll likely have the existing user profiles we created for Registration - plus some more. What do we need to add to our registration user profiles?

Acceptance Criteria:
- [x] Ideate other user groups that will interact with the reporting app that are not currently in our registration user profiles
- [x] Create rough user profiles of additional users identified
- [x] Pass profiles to scrum team for feedback
- [x] Create a table to show how user profiles differ from each other
- [x] Pass to PO for feedback
- [x] Pass profiles to SME(s) for feedback

Goal of ticket:
Get a better idea of who will be interacting with reporting system

**Comment by jaimiebutton** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-reporting/12?planning-poker) with Zenhub @nanyangpro @NicoleGovvy

**Comment by jaimiebutton** [comment]
Hey @patriciarussellCAS - would love your thoughts on when we'd consider this ticket 'done'

**Comment by patriciarussellCAS** [comment]
@jaimiebutton should we have these verified by Harnav before closing?

**Comment by jaimiebutton** [comment]
Hey @patriciarussellCAS , you can check out the updated profiles over on the Miro board. Will hopefully borrow Harnav's eyes for a final look over the next couple days!

**Comment by jaimiebutton** [comment]
Update - have gotten green light from Harnav. Have follow-up questions about:

- The need for an Operational Representative profile
- The need to have a few 'super users' who can change industry data if/as needed.

**Comment by patriciarussellCAS** [comment]
My thoughts: We could close this ticket and then create a new ticket for "potential additional users". I think we have enough info on the main user profiles to move ahead to next steps, but good to flag in another ticket that we may need to consider others as we learn more. I wouldn't want these questions to block us. Does this work for you @jaimiebutton ?
