### ISSUE TITLE
Conduct external validation for report submission

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/cas-reporting#121]
Now that we have planned our user validation sessions out, we're ready to do them! We want to conduct user research sessions for validating/confirming operator report data entry/submission and user roles.

- [x] Confirm CAS/DTS attendees at session
- [x] Conduct session 1
- [x] Conduct session 2
- [x] Conduct session 3
- [x] Conduct session 4
- [x] Conduct session 5
- [x] Document sessions in Miro

**Comment by patriciarussellCAS** [comment]
Great work. Thanks!
