### ISSUE TITLE
Create ERD for reporting

### ISSUE THREAD

**Issue by mikevespi** [bcgov/cas-reporting#122]
#### Describe the task

Now that we have the general structure of a report sorted out, we need to map it out into an entity relation diagram. The resulting model will continue to evelove, but we need to get a first version done to  be able to start building it out. This first iteration needs to include the major components of an annual report, and any lookup tables needed. It should also be flexible / forgiving enough to allow for the further customization ahead (e.g. handling various report types, or adding a custom fuel). The business area should be given a chance to review this model as well, since they will be querying and working with the data.

As a part of this process, it would be a good idea to establish how Moose, Giraffe and BA will communicate when changes need to be made to the model.

#### Acceptance Criteria
- [ ] An ERD of how we will represent report data in the data base has been made
- [ ] Business Area and DST are in agreement on the data model (based on current understanding)
- [ ] NRIDS data architects have seen the ERD and provided feedback

#### Definition of Done
- [ ] The entity relationship diagram representing the data needed to assess reports is accessible to all who need it
- [ ] Process for making / requesting updates to the model are in place and documented

#### Blocked by
- #169 
#### Blocking
- #168

**Comment by patriciarussellCAS** [comment]
@mikevespi given the amount of work required for this I'm wondering if we can break this down into sprint-sized chunks of work. Thoughts?
I will create a ticket to capture the first part of work that IRC is doing to go through the SWRS spreadsheet as I believe that blocks much of this ticket's work.

**Comment by patriciarussellCAS** [comment]
Should this get pushed to next sprint backlog? @mikevespi

**Comment by rdromey** [comment]
@mikevespi to break down into more discrete pieces

**Comment by pbastia** [comment]
Breaking it down
- emissions (excluding mandatory extra fields from WCI/regs) 
- production
- annual report section 2

**Comment by mikevespi** [comment]
Broken down into #227 and #228 .
Will discuss at refinement if we need a card for annual report section 2.
