### ISSUE TITLE
Determine report data architecture for versioning and storage

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-reporting#126]
#### Describe the task

- How are we saving the report data as it's being submitted? This is crucial to have visibility on the work needed to implement the reporting piece

- We should  aslo decide on how we're going to version reports and what that translates to as far as database structures & dependencies.
In CIIP, we had an application table & an application revision_table which had a composite key of application_id & version_number. The outcome of https://github.com/bcgov/cas-reporting/issues/126 may have an effect on this decision (or vice versa).

Question: how will this data be queried?
JSON data as in CIIP? Table data? How can we version report format and requirements?

#### Acceptance Criteria

- [ ] A small piece of documentation on the features this needs to support (versioning, querying, etc)
- [ ] Technical answers to the features above
- [ ] A data model outlining all the pieces of a report, and the relationships with the other
- [ ] A breakdown of the different implementation items, to be translated into cards

#### Additional context
 
- To be completed by the end of this sprint, but the sooner the better

Blocking
#219

**Comment by pbastia** [comment]
Initial thoughts are:
- unstructured data (JSON) will reduce the amount of maintenance work as opposed to individual tables per activity/source type
- unstructured data will also make it easier to store different versions of a schema
- We would like to make it easy to grab the latest submitted version of an application

**Comment by patriciarussellCAS** [comment]
As discussed in refinement - this needs a follow-up ticket. To confirm if that's been created or not.

**Comment by pbastia** [comment]
This could probably use a 3 amigos type discussion with the BA, once we have a first draft of the features we would like

**Comment by patriciarussellCAS** [comment]
Does this ticket need to be refined? I see that a follow-up ticket has been created based on this one. Let me know if we can leave as is, or need to change the scope? thanks!

**Comment by rdromey** [comment]
@pbastia to merge with #258

**Comment by pbastia** [comment]
Dev meeting scheduled for June 17

**Comment by patriciarussellCAS** [comment]
Note: we have two tickets that are somewhat related to saving:
#130 (have continuous auto-save) is a potential feature that users would like - we may not be able to do this, and Registration have decided NOT to use this feature. 
#198 (user story that allows users to save their progress before submitting a report)
