### ISSUE TITLE
Glossary Feature: Design

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/cas-reporting#131]
Industry users have expressed a need for more clarity on terms, data fields and calculations used throughout our app. 
In user testing sessions we had positive feedback for the glossary feature - the allows users to link to the glossary page from each page in the reporting (and registration?) app.

This is a preliminary design ticket. We will need follow-up dev tickets for this as well. 

Question: How can we give users the ability to view/use the glossary without losing their place in the report? 

Note that this is different than guidance documents, which will outline the how to. The glossary will indicate the why

Acceptance Criteria: 
Given that I am an Industry Reporter in BCIERS
Then I want access to a glossary page with information on terms and calculations used throughout the system
So that I can understand a) what I'm being asked to input and b) where certain calculations/information came from
*I would like to access this glossary WITHOUT losing my place in my annual reporting process*

- [x] Compile all the feedback from user research that indicated requiring glossary explanantion
- [x] Create a Miro workshop to share these ideas with Business area
- [x] Meet with Jess' team to talk about intentions of the glossary page
- [x] make a plan for future collaboration with them (adding in terms in the glossary)
- [x] Add words in the master glossary
- [x] Review existing design solution in Giraffe collaboration
- [x] Coordinate with Zoey to evaluate how to present this in the UI
- [x] Create tickets for further implementation

**Comment by suhafa** [comment]
@patriciarussellCAS @hannavovk How about we repurpose this to be for the Glossary/Guidance document work for the app? cc: @zoeyli-46

**Comment by patriciarussellCAS** [comment]
@suhafa that works for me!

**Comment by patriciarussellCAS** [comment]
@suhafa I've added an AC. Anything else needed here or can we take the backlog refinement tag off?

**Comment by suhafa** [comment]
Thanks @patriciarussellCAS ! Updated the ticket further to include engagement with Jess' team and creating further tickets

**Comment by suhafa** [comment]
The terms from Reporting have been shared with Jess' team, and we anticipate Registration and COAM terms, as well as overall BCIERS terms to be updated in the future. 
Zoey and I met and [created a solution for the UI](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=13864-3957&t=oB3Uq9Ir2mu0utaD-1) that is to be discussed and determined with Devs as for its implementation.
I have created a dev ticket #334 for Glossary page implementation.
