### ISSUE TITLE
As a Industry Reporter, I want to upload attachments as part of the emissions report process

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/cas-reporting#134]
As an Industry Reporter, I want to be able to upload attachments so that I can meet the requirements of my Annual Reports. 

The system will need to support the ability to upload documents in multiple formats. 
This will include: 
1. List of Equipment (as required by a specific WCI methodology) - this will only apply to LFOs and will likely be added as part of the emissions report section - this will uploaded in the Attachments page
2. Confidentiality Request form - [Wireframe](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=17438-5041&t=se71XdaQ8MPFB2OX-4)
3. Process flow diagrams and Boundary files - these are uploaded in Registration
4.  Verification statements - this specific upload is captured in ticket #200 and will happen on the verification step of the annual report

These are all of the uploads that have been identified by the BA as of June 2024.

**Comment by patriciarussellCAS** [comment]
Questions to clarify:
How is this being dealt with in Registration? 
What at a minimum do we need to have available as an option for Reporting? For example; is a final verification statement (PDF?) the only thing they need to upload? What else should we consider?

**Comment by patriciarussellCAS** [comment]
@zoeyli-46 - I think we just need clarification from devs that it makes sense to have item number 1 get uploaded on the "Attachment uploads" page as opposed to having users upload those documents as part of the activities workflow. 
I believe we agreed with the BA that this was ok, but haven't confirmed with Devs. Once we have clarity on that I think this ticket is good to close. Thanks,

**Comment by zoeyli-46** [comment]
Hey @patriciarussellCAS it was confirmed with Pierre in this thread [here](https://teams.microsoft.com/l/message/19:9c5f0a21a61d47f6843c9bee7be692cd@thread.tacv2/1728598442351?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&groupId=29821293-3244-455d-beae-e01d27762cfe&parentMessageId=1728598442351&teamName=External%3A%20CAS%20-%20Clean%20Growth%20Digital%20Service%20Team&channelName=Designers%20Internal&createdTime=1728598442351&ngc=true)

I will close out this ticket :)
