### ISSUE TITLE
Reporting Module Access for Industry Users

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/cas-reporting#136]
As an Industry User I want to have access to the Reporting module early so that I can have enough time to fill out my report before the deadline. 
There should be a clear "end" to a reporting cycle, so that anything submitted after midnight on May 31st would be considered "late". 

Note: The submission window will likely open a few months before the May 31 deadline (currently in SWRS its ~3-4 months before). We don't want it open TOO early while there may be reconciliation of previous reports going on. Will need to confirm with IRC when to "open" the module

**Comment by patriciarussellCAS** [comment]
To clarify: Do you mean give users access to the Reporting module well in advance of the deadline so they can start a report and then save it in draft so they can come back later to complete and submit it? 
I believe this is how SWRS is set up and they typically have a few months to go in and work on their reports so would guess they'll want something similar. Another good one to chat with business area about.

**Comment by NicoleGovvy** [comment]
@patriciarussellCAS - yes! Early access (or open access?) to the module for starting data entry.

**Comment by mikevespi** [comment]
I think there are two ideas that need to be detatched from eachother conceptually: the reporting module, and the process of filing a report. The reporting module is where you would go to file a report, but it also houses other and past reports etc. So access to the module should always be available. As for beginning to file a report, I think it would make sense to be able to start entering data about a period as soon as that period ends. That being said  we should confirm with business area in my opinion. It's possible that circumstances exist when that isn't the case.

**Comment by pbastia** [comment]
That's a good question @mikevespi. If we follow CIIP we only allow people to login and enter data at the start of the reporting period for the given year. This allows the program to setup the specifics for each year and to avoid making business changes while some people have already started filling out information

**Comment by rdromey** [comment]
Replaced with #193
