### ISSUE TITLE
Identify users for reporting research/usability testing

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/cas-reporting#15]
####Goal of Ticket
Have a clear understanding of the types and numbers of operators and which role within the operator itself we want to conduct research/testing with.

#### Describe the task

Understand who we need to do research/testing with for OBPS reporting and registration.

#### Acceptance Criteria

- [x] Identify attributes of operators we want to have participate
- [x] Identify number of operators
- [x] Confirm with business area
- [x] Confirm with POs

#### Additional context
Note this isn't identifying specific people but rather the profile we want to speak with.

**Comment by nanyangpro** [comment]
Added Moose tag so that @suhafa is aware and in the loop. :)
