### ISSUE TITLE
Tech Debt: ESLint action needs caching

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-reporting#154]
### Description of the Tech Debt

Currently the ESLint action installs all the yarn dependencies every time
It could be using a cache from the setup dev env action, or implement its own cache

#### Tech Debt Triage

The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

#### Risk Value Scoring:

| Level  | Value                 |
| ------ | --------------------- |
| High   | <div align="center">3 |
| Medium | <div align="center">2 |
| Low    | <div align="center">1 |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |       |       |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |       |       |
| System Fault Risk - Risk of system errors or application downtime                                                             |       |       |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |       |       |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |       |       |
| <div align="right">**TOTAL SCORE:**                                                                                           |       |       |

**Comment by rdromey** [comment]
Moving to monorepo model, no longer necessary, already done in cas-registration
