### ISSUE TITLE
Contribution guidelines for parallel development with Registration

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-reporting#159]
#### Description:

A .md file outlining the contribution guidelines for the reporting app.
There is just a bit of thinking to do on how exactly this is going to work.
The first idea is to merge all the work on a separate `giraffe-develop` branch, and to rebase that branch as often as possible from the registration official `develop`

This is experimental, and those guidelines are meant to be adjusted in the future.

#### Acceptance Criteria:

Given I am a developer on the reporting app
When I write code for the app
Then I have a list of contribution guidelines

#### Development Checklist:

- [x] a .md file in the `docs` folder
- [x] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
@patriciarussellCAS you can see the writeup here https://github.com/bcgov/cas-home/blob/main/docs/giraffeContributionGuidelines.md

**Comment by patriciarussellCAS** [comment]
Thanks @pbastia - these look good to me. Has a senior dev from Moose had a look as well? It would be nice to have their okay as well, before I close this ticket. Also, is there a place to share this on Scrum team? Or is just in github enough? Thanks!

**Comment by pbastia** [comment]
flagging @dleard and @andrea-williams for an extra review :)
