### ISSUE TITLE
Take inventory of engagement team's user data

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-reporting#16]
The ICPG team has a bunch of data on our industrial users! To make sure that work is known to our team, let's take a moment to document what's available to us at a high-level for whenever it's helpful down the line.

Acceptance Criteria:
- [ ] Create a space in Miro to hold this
- [ ] Check in with engagement team about what they think would be relevant for our team
- [ ] Document known folders/files/pieces of work from the Engagement team's Teams Channel that would be of use
- [ ] Pull out any insights that are immediately useful, if any
- [ ] Make a plan to keep this documentation up-to-date(ish), if deemed helpful

Objective of ticket:
- Ensure we're making use of the work the engagement team is doing
- Have an easy-to-view resource we can come to when looking for data in the future

**Comment by patriciarussellCAS** [comment]
Hey @jaimiebutton  and @NicoleGovvy - do we still think this ticket is relevant? I wonder if it's no longer necessary. Thoughts?
