### ISSUE TITLE
Reporting user story mapping rollup

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/cas-reporting#162]
- [x] Refine existing user story map
- [x] set up sessions to validate user story map (Emilie, Harnav, Jairo, Amos)
- [x] Update user story map
- [x]  Create backlog tickets based on requirements

**Comment by NicoleGovvy** [comment]
@patriciarussellCAS  @suhafa user story mapping part 2

**Comment by suhafa** [comment]
Refined user story map [here](https://miro.com/app/board/uXjVN4hyuug=/)

**Comment by suhafa** [comment]
Tickets added, user story map refined!
