### ISSUE TITLE
Separate frontend container

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-reporting#163]
#### Description:

As a developer,
I want the reporting app to be in its own, standalone frontend deployment
And it should connect to the common API

#### Acceptance Criteria:

Separate webserver for the reporting pages
This might require separate keycloak authentication in the beginning (since this is a separate webserver and we don't have a mechanism to share sessions as of yet)

Separate dockerfile
(or a crafty docker build process with separate pages?)

#### Development Checklist:

- [ ] a barebones Next app from our `reporting` repository
- [ ] a dockerfile from our `reporting` repository
- [ ] the root URL for the pages is served on the `/reporting`path
- [ ] duplicate code from the registration app should be abstracted and pulled together at the build stage
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Blocking

This is blocking #108 
This is blocking #123 

#### Notes:

-

**Comment by rdromey** [comment]
Being absorbed by #165
