### ISSUE TITLE
Shipit target for funny namespace from giraffe-develop branch

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-reporting#164]
#### Describe the task

Automate the deployment of `giraffe-develop` to the funny namespace

#### Acceptance Criteria

- [ ] a `shipit.yaml` file allowing us to deploy the helm chart to the funny namespace
- [ ] a new shipit stack for that namespace
- [ ] a `values-giraffe` for the helm chart, maybe?

**Comment by patriciarussellCAS** [comment]
Would this ticket change if we move away from Shipit???

**Comment by pbastia** [comment]
Yes! Although switching away from shipit is a medium-term goal (if we do it) so we'd still need this ticket for now. This is very low effort

**Comment by BallardRobinett** [comment]
Using the CIF-tools namespace (c53ff1-tools) instead because we seem to have lost the funny namespace.

**Comment by patriciarussellCAS** [comment]
Follow-up task card being created.
