### ISSUE TITLE
Task: deploy cas-obps-postgres and registration/reporting app in the funny namespace

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-reporting#165]
#### Describe the task

Manual deployment of the registration app + database to a temporary namespace. We'll use CIF tools for now.
This should ideally be done with the helm chart and the make install script, configured properly. Optionally done directly from Nx monorepo tooling.

#### Acceptance Criteria

- [x] Manual deployment of `giraffe-develop` branch to tools namespace
- [x] Nx used for deployment of _Reporting_
  - [x] Configure Nx target to handle build/deployment
  - [x] a barebones Next app from our reporting repository
  - [x] a dockerfile from our reporting repository
  - [x] the root URL for the pages is served on the /reportingpath
  - [ ] ~~duplicate code from the registration app should be abstracted and pulled together at the build stage~~ Moved to new ticket #181

**Comment by joshgamache** [comment]
Going to use this ticket to document findings for deployment utilizing Nx monorepo tooling.

**Comment by BallardRobinett** [comment]
note: funny namespace no longer exists so we are using the CIF-tools namespace (c53ff1-tools)
