### ISSUE TITLE
Prepare draft workflow for reporting

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-reporting#166]
Based off the work that Nan and Zoey are doing for registration, let's try to create workflows on the basis of the cleaned up user story map to identify the workflow of registration from the get go

Draft = version that gives us a high level vision, but doesn't have all the tiny details due to unknowns

Acceptance criteria
- [x] sync with the work Nan & Zoey did to understand what fields affect reporting from registration
- [x] create basic workflow on the basis of the cleaned up user story map
- [x] add in edge cases to consider (Reporting-only, New Entrants, EIOs, etc)
- [x] consult with SMEs & POs & Devs once draft is completed
- [x] refine draft 
- [ ] consider identifying unhappy paths (optional)
- [ ] Create backlog tickets

Blocking #167

**Comment by suhafa** [comment]
@patriciarussellCAS created this ticket to capture the pre-wireframes work we can finally do at this point ;D

**Comment by zoeyli-46** [comment]
For acceptance criteria 1, we currently are unclear what fields from registration will affect reporting. However, meeting with IRC folks could answer this. 

I was also trying to understand this, so I asked Harnav which registration fields affect reporting and she said "(this is only my opinion IRC needs to discuss this) Naics code, product name, reporting activities will be used" so we could book a meeting with some IRC folks and workshop this?

Btw, @nanyangpro looping you in the conversation, in case you have talked with business areas about this and have some input!

**Comment by suhafa** [comment]
@patriciarussellCAS following today's session, I think this ticket can be closed. As for creating 'backlog tickets' in the AC, since that work is being covered in the user story mapping work, we can ignore it here. As for the 'unhappy paths' discussion (marked here as optional), I think that should be a separate amount of work once meant for designer-dev collab, and it may be a bit too early for it. I'm not sure yet if we need a ticket for that or if that will be what we end up doing any way as part of data fields work.

Having said that all that, this ticket can be closed!

**Comment by patriciarussellCAS** [comment]
New ticket being created for unhappy paths. this is closed.
