### ISSUE TITLE
Create lo-fi visuals of reporting for user engagement

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-reporting#167]
For our user engagement we need visuals to portray some questions. Moreover, it would be helpful to create lofi wireframes that reflect our latest understanding of the system.

- [x] Have meeting with Harnav to understand BCGHG fields
- [x] create lo fi mocks that showcase a basic reporting workflow
- [x] customize each mock to the sector our volunteering users represent (NOT REQUIRED)
- [x] review these mocks with SMEs/designers/PO/devs during Giraffe Collab session
- [x] refine mock ups

Blocking #161

**Comment by suhafa** [comment]
@patriciarussellCAS created this ticket to capture the work for creating lo-fi mocks or visuals to support user engagement efforts. I see this ticket as also laying the foundation of the reporting workflow

**Comment by suhafa** [comment]
[Lo-fi mocks and prototypes](https://www.figma.com/proto/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?page-id=6914%3A479&type=design&node-id=6914-479&viewport=1573%2C41%2C0.17&t=sqqH3L8hQSr6OtzZ-1&scaling=min-zoom&starting-point-node-id=6984%3A5689&show-proto-sidebar=1&mode=design) created @patriciarussellCAS @NicoleGovvy @zoeyli-46 
FYI, some context: Had a chat with Harnav earlier today about the report summary. For SFOs, they will report on only one facility and therefore can generate a report summary because report summary, I learnt, applied to Operation only, not facilities.
For LFOs, we need to confirm how we will generate a report summary because each facility will need to be reported individually first, then a cumulative report once all the reports are submitted. This remains open-ended and so, I pulled out our report summary from the prototypes for now and will add it back in once Harnav or our BA can confirm.

**Comment by patriciarussellCAS** [comment]
Thanks Suha! Looks good to me :)

**Comment by NicoleGovvy** [comment]
@suhafa - these are wonderful, thank you!
