### ISSUE TITLE
Reporting Data Fields Spreadsheet by IRC

### ISSUE THREAD

**Issue by patriciarussellCAS** [bcgov/cas-reporting#169]
#### Describe the task

The Business Area will take the current SWRS spreadsheet (created by Andrea and edited by Amos in July 2023) and work off of this to create an up-to-date, verified artifact that will include all the data fields required for reporting. This work will support the ERD work for ticket #122 

#### Acceptance Criteria

- [x] DST (Developers, UX, PO) review the current spreadsheet and confirm what information we need for each data field. Add any columns as needed (for example, we want a description of the metadata for each field, so need to add a column for that in the spreadsheet) - **DUE March 8**
- [x] Set a deadline for this work and support IRC as needed
         - [ ] Currently requesting a final version by the end of June 2024
- [ ] Have a "completed" spreadsheet to use for future ERD work.  

#### Additional context

- The responsibility for this ticket is mainly with IRC, however they need DST support. Because other work on DST is dependent on IRC's work we can use this ticket to show where it's blocking other tickets. 

#### Blocking

This ticket is blocking ticket #122

**Comment by mikevespi** [comment]
@patriciarussellCAS do you happen to know if the spreadsheet is finalized? At least for this iteration?

**Comment by patriciarussellCAS** [comment]
@mikevespi from what Jairo has told me, this new version is "mostly" finalized, he's just adding in some additional information for LFOs. 
I think we can use version 2 for initial work but I would recommend starting with SFOs (so avoid oil and gas users for now). I will push IRC for a final deadline of April 24 but really hope to have something sooner. Let me know if you have thoughts/concerns!

**Comment by patriciarussellCAS** [comment]
Update April 26: Emilie will do another review of the latest version, however we feel that this is very close to final. If needed this may get reviewed by Konstantin in IRC. Will keep in the "in progress" column for now.

**Comment by patriciarussellCAS** [comment]
This has expanded to a number of different spreadsheets but the IRC team is trying to consolidate these into one source of truth.

**Comment by patriciarussellCAS** [comment]
Review has been split into 4 "batches". As of July 15th Batch 1 & 2 have been approved. Still waiting for Batch 3 & 4.
