### ISSUE TITLE
Brainstorm KPIs/Metrics for the OBPS System

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-reporting#17]
Key Performance Indicators (KPIs) allow us to measure how well we're delivering our service. In ideating our KPIs, we can come to common understanding of our definition of success for our new system. Useful KPIs are often specific, measurable, attainable, and time-bound -and should be evaluated & re-evaluated over time.

Acceptance Criteria:
- [ ] Add to me! (how should we go about doing this work?)

Goal of the ticket:
- Ideate what success looks like in the OBPS system
- Brainstorm metrics that can be collected to evaluate our success over time

**Comment by NicoleGovvy** [comment]
@patriciarussellCAS we can close this I think, #47 is a more fleshed out version of this.
