### ISSUE TITLE
DevOps maintenance

### ISSUE THREAD

**Issue by mikevespi** [bcgov/cas-reporting#172]
There are some tasks that we need to do on a regular basis as a part of our ongoing devops maintenance. A list of which resources have been covered so far can be found [here](https://bcgov.sharepoint.com/:w:/r/teams/00608-Developers/Shared%20Documents/Developers/Secret%20resets/secret_reset_log.docx?d=web3fd43aec1c459fbb8605621764a987&csf=1&web=1&e=2KffbC), and the process itself can be found [here](https://bcgov.sharepoint.com/:w:/r/teams/00608-Developers/Shared%20Documents/Developers/Secret%20resets/database_pw_reset_process.docx?d=wb039eb01a16b4425949fb5f6640c507a&csf=1&web=1&e=oWlLwZ).

Good opportunity for training to deploy to dev

**Comment by mikevespi** [comment]
@patriciarussellCAS Andrea and I finished this today. There isn't really a simple way to verify it, but there is a document in Scrum Team that lists what has been done, and where.

**Comment by patriciarussellCAS** [comment]
Awesome, thanks Mike!
