### ISSUE TITLE
Research spike: Nx bonuses

### ISSUE THREAD

**Issue by joshgamache** [bcgov/cas-reporting#174]
A timeboxed research spike to explore the features outside of our core requirements for Nx. Will try to evaluate for any quick wins and considerations on implementation time vs value. 
[2-3 days]

## Known features to investigate
- Self-hosted remote caching (Nx Replay)
  - Cache to GCP bucket? Artifactory?
- Self-hosted remote task execution (Nx Agents)
  - Github actions? OpenShift jobs?
- Releases (Nx Release)
  - Drop in replacement for our Release-it module?
- Github PR integrations
- Code generation
  - Automatic documentation for components, API?
- Plugins
  - Nx Playwright for E2E
  - ~~Nx Jest for unit testing~~ _Already implemented Vitest_
  - Image builds ([Nx Container](https://github.com/gperdomor/nx-tools) is already in use for Reporting, optimizations likely)
  - Linting
  - SonarQube

## Questions
- Estimated effort?
- Developer adoption effort (automatic or needs training)?
- What part of the process does this target (DevOps, Dev experience, Security, etc)?
- Maintenance complexity/considerations?
- Technical limitations (esp. resource requirements)
- **R**each **I**mpact **C**onfidence **E**ffort score?

**Comment by patriciarussellCAS** [comment]
Should this be pulled into Sprint 11? @joshgamache

**Comment by joshgamache** [comment]
@patriciarussellCAS 
> Should this be pulled into Sprint 11? [@joshgamache](https://github.com/joshgamache)

Probably a good candidate as a _stretch goal_!

**Comment by pbastia** [comment]
Suggestion:
- timebox this as a short research
- write cards for each individual feature that we deem interesting for the team, that we can then estimate and schedule depending on their individual value

**Comment by joshgamache** [comment]
Research and analysis is posted [here in the Sharepoint](https://bcgov.sharepoint.com/:w:/r/teams/00608-ScrumTeam/Shared%20Documents/Scrum%20Team/OBPS/Tech%20Stack%20Decisions/Nx%20Monorepo%20further%20feature%20research.docx?d=w1e41e1927ce84495950e8bc27bd68389&csf=1&web=1&e=GpEdhQ).

**Comment by pbastia** [comment]
Left to do: Write cards about the features we think we'd like to implement one day. Document the ones we won't in this card.

**Comment by joshgamache** [comment]
Tickets were created:
- bcgov/cas-reporting#232 - Nx Affected, cache
- bcgov/cas-reporting#240 - Nx Release
- bcgov/cas-reporting#239 - Nx Affected (but for Docker containers)
- bcgov/cas-reporting#241 - Nx Atomizer(E2E)
- bcgov/cas-reporting#242 - Nx Cloud, Nx Replay

Not implemented:
- Code generation: wait and see

Won't (likely) implement:
- Nx Agents
