### ISSUE TITLE
Discovery: Alternate Methodology

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-reporting#175]
#### Goal of Ticket
In SWRS, users can choose WCI methodology specific to their activity. In rare use cases, the operation would want to use an alternate methodology to calculate their emissions. This has happened in the past. This ticket is to explore alternate methodologies and research into it in depth

Some questions to deep dive:
- Can accepted alternative methodologies be used across different industrial operators? 
- What is the approval process like? 

#### Describe the task

Research, ask users and business area about alternate methodology. Potentially do user engagement sessions with operations who may have opted for this.

#### Acceptance Criteria

- [x] Bring up alternate methodology as a discussion point in Giraffe Collab. 
- [x] Note all the technicalities and create a follow up plan after the discussion
- [x] If required, meet SMEs one-on-one to dig deeper
- [ ] Prepare wireframes as a visual solution
- [ ] review wireframes with devs and BA in the following Giraffe collaboration
- [ ] Document final decision
- [ ] create user story ticket

#### Definition of Ready:

Note: If any of the points are not applicable: delete or mark N/A

- [ ] Topic is clearly Defined.
- [ ] Task Description is Clear.
- [ ] People to speak to are identified (if applicable).
- [ ] Acceptance Criteria is Clear.
- [ ] Ticket Title is Clear.
- [ ] Ticket is reasonably Split up/sized.
- [ ] Value/Pain is Clear.
- [ ] Relevant Team Members are assigned.
- [ ] Ticket Estimated.

#### Definition of Done.

Note: If any of the points are not applicable: delete or mark N/A

- [ ] Rough User Stories Proposed.
- [ ] Follow-up Tickets created (if necessary).
- [ ] Findings are documented (if necessary).
- [ ] Reference docs/spreadsheets identified and indexed.
- [ ] Value Proposition Canvas (if required)

**Comment by rdromey** [comment]
@patriciarussellCAS Testing for notifications

**Comment by suhafa** [comment]
Waiting on business area for clarification:

- Alternate Methodology vs Replacement Methodology vs Alternative Parameters are same but different. They all require a description, but there are requirements like Director's approval for one, needing user to declare emissions for another. Alternate Methodology however is not explicitly mentioned in GGERR. 
- BA to confirm if the three can be clubbed together and confirm their difference
- Suha suggested having the three of them separate and having a text template in the description box that shows the user how we expect them to input their description. They can change it if they want. It will be required.

**Comment by suhafa** [comment]
Notes from BA:
"For the Methodology Dropdown list, there be 2 separate options: "Replacement Methodology" and "Alternative Parameter Measurement Methodology"

Upon selecting either of these aforementioned 2 options, there be a note (through an asterisk or similar) with the following text: “By selecting Replacement Methodology/Alternative Parameter Measurement Methodology, you may be contacted by Ministry staff to verify compliance.”

Following selection of either of the 2 options, a mandatory comment box will appear with a note above the comment box “Replacement Methodology/Alternative Parameter Measurement Methodology Description”"

This ticket can be converted to a dev ticket for implementation of this, unblocked ticket

**Comment by suhafa** [comment]
Coordinate with designer for how to implement the note

**Comment by suhafa** [comment]
Confirmed with BA: the decision was made not to include "Alternate Methodology"

**Comment by rdromey** [comment]
BA decision made, ticket closed. See comments above. Ticket created around the description box.
