### ISSUE TITLE
Discovery: Workflow for allocation of emissions to products

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-reporting#177]
#### Goal of Ticket
Understand the process for allocating of emissions in order to add it to our workflow artifacts. 

#### Describe the task

Understand and align understanding across the business area as to how the allocation of emissions to products should be. Could potentially use a visual to understand the relationship.

#### Acceptance Criteria

- [x] Review the flowcharts BA have made and get clarity on the desired workflow
- [x] Create a draft visual showing the relationship of emissions to products
- [x] (optional) if required, create some lo-fi mocks
- [x] share visual with Team Moose + SMEs
- [x] refine visual on the basis of feedback
- [x] update user story map + draft workflow 

#### Additional context

Add any other context about the task here.

#### Definition of Ready:

Note: If any of the points are not applicable: delete or mark N/A

- [ ] Topic is clearly Defined.
- [ ] Task Description is Clear.
- [ ] People to speak to are identified (if applicable).
- [ ] Acceptance Criteria is Clear.
- [ ] Ticket Title is Clear.
- [ ] Ticket is reasonably Split up/sized.
- [ ] Value/Pain is Clear.
- [ ] Relevant Team Members are assigned.
- [ ] Ticket Estimated.

#### Definition of Done.

Note: If any of the points are not applicable: delete or mark N/A

- [x] Rough User Stories Proposed.
- [x] Follow-up Tickets created (if necessary).
- [x] Findings are documented (if necessary).
- [ ] Reference docs/spreadsheets identified and indexed.
- [ ] Value Proposition Canvas (if required)

**Comment by patriciarussellCAS** [comment]
Update from Giraffe Collab: Jairo thinks that allocation of emissions could happen as part of the work flow for each Activity, as opposed as a whole new page at the end of the workflow.

**Comment by patriciarussellCAS** [comment]
Hey @suhafa based on the meeting today it sounds like we have a decision from BA on this: Allocation of emissions to be under each Activity subsection, not separate. It will be reported in tonnes not %, but HAS to be equivalent to 100% as required in the regs
Do you think it makes sense to close this ticket and then we can create a user story ticket for the process of allocating emissions?

**Comment by suhafa** [comment]
Good to be closed, reflected the BA decision. Something to consider and collaborate on potentially which is "HAS to be equivalent to 100% as required in the regs", should we show this visually somehow?
