### ISSUE TITLE
Discovery: Version history feature

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-reporting#178]
#### Describe the task

We need to learn how users and the business area would prefer to set up version history and editing. Requires communicating with devs as to the feasibility and looking into existing solutions for this.

Ticket #176 may closely inform the progress of this ticket as well. This may be informed by work being done in the supplementary reports discovery

#### Acceptance Criteria

- [x] book a session with devs to understand how we can approach version history, and examples of it in past apps, understanding how we want to go about supplementary/corrective reports (touches upon the work being done in #176)
- [x] design a workflow(s) to come up with some solutions for MVP
- [x] Make wireframes
- [x] share with team and business area for feedback
- [x] ensure BA is in alignment about those decisions
- [ ] refine wireframes + workflow

#### Additional context

Add any other context about the task here.

#### Definition of Ready:

Note: If any of the points are not applicable: delete or mark N/A

- [ ] Topic is clearly Defined.
- [ ] Task Description is Clear.
- [ ] People to speak to are identified (if applicable).
- [ ] Acceptance Criteria is Clear.
- [ ] Ticket Title is Clear.
- [ ] Ticket is reasonably Split up/sized.
- [ ] Value/Pain is Clear.
- [ ] Relevant Team Members are assigned.
- [ ] Ticket Estimated.

#### Definition of Done.

Note: If any of the points are not applicable: delete or mark N/A

- [ ] Rough User Stories Proposed.
- [ ] Follow-up Tickets created (if necessary).
- [ ] Findings are documented (if necessary).
- [ ] Reference docs/spreadsheets identified and indexed.
- [ ] Value Proposition Canvas (if required)

**Comment by mikevespi** [comment]
Related to https://github.com/orgs/bcgov/projects/123/views/1?filterQuery=-status%3Adone+report&pane=issue&itemId=57276041 , we'll keep you up to date on that discussion as it happens @suhafa

**Comment by suhafa** [comment]
During Giraffe Collab on May 1, wireframes were reviewed. 
Next steps:
- confirm with John about how to approach the language for Corrected vs Supplementary reports
- Meet with Mike to talk about statuses and feasibility of the design

**Comment by rdromey** [comment]
Completed with those discussions happening captured in #176
