### ISSUE TITLE
Reporting Module: Create Fuels lookup table

### ISSUE THREAD

**Issue by mikevespi** [bcgov/cas-reporting#180]
#### Describe the task

Part of the reporting process involves operators selecting the fuels that they used. We need a lookup table to hold the list of potential fuels along with their unit, fuel classification, and emission type (confirm with BA). The [BCGHG Fields for BCIERS](https://bcgov.sharepoint.com/:x:/r/teams/00608-CPRInternal/Shared%20Documents/Carbon%20Pricing%20Transition%20SMEs/Reporting%20App/BCIERS%20Reporting%20Fields%20v2.xlsx?d=wb661365000eb422fa10341608cd0e2e6&csf=1&web=1&e=ufch43) contains the most up to date list. Still to be confirmed with business area.

#### Acceptance Criteria

- [x] List of fuels and relevant fields confirmed with BA
- [x] Lookup table exists with latest approved values
- [x] Table has name and units columns

**Note:** If we do not have a confirmed set of fuels from BA when this work is started, let's create the table & add ~3 demo fuels. We can replace those fuels with the actual list when we receive it.

#### Additional context
This table could potentially get updated over time so needs to be editable.

**Comment by patriciarussellCAS** [comment]
@mikevespi will refine this ticket

**Comment by BallardRobinett** [comment]
Making a name and units column. The new rows that have been added (highlighted) are missing units.

**Comment by patriciarussellCAS** [comment]
@BallardRobinett Jairo has made a new spreadsheet with the units split out and refined list of fuels. Can you use this one for now? [Fuels](https://bcgov.sharepoint.com/:x:/r/teams/00608-CPRInternal/Shared%20Documents/Carbon%20Pricing%20Transition%20SMEs/Reporting%20App/BCIERS%20Reporting%20Fields%20v2.xlsx?d=wb661365000eb422fa10341608cd0e2e6&csf=1&web=1&e=ufch43)

**Comment by BallardRobinett** [comment]
> @BallardRobinett Jairo has made a new spreadsheet with the units split out and refined list of fuels. Can you use this one for now? [Fuels](https://bcgov.sharepoint.com/:x:/r/teams/00608-CPRInternal/Shared%20Documents/Carbon%20Pricing%20Transition%20SMEs/Reporting%20App/BCIERS%20Reporting%20Fields%20v2.xlsx?d=wb661365000eb422fa10341608cd0e2e6&csf=1&web=1&e=ufch43)

@patriciarussellCAS Yes this is good. To confirm, I'm going to include all the highlighted yellow and red elements too? And some of them will just have a blank for the unit type column?

**Comment by patriciarussellCAS** [comment]
> > @BallardRobinett Jairo has made a new spreadsheet with the units split out and refined list of fuels. Can you use this one for now? [Fuels](https://bcgov.sharepoint.com/:x:/r/teams/00608-CPRInternal/Shared%20Documents/Carbon%20Pricing%20Transition%20SMEs/Reporting%20App/BCIERS%20Reporting%20Fields%20v2.xlsx?d=wb661365000eb422fa10341608cd0e2e6&csf=1&web=1&e=ufch43)
> 
> @patriciarussellCAS Yes this is good. To confirm, I'm going to include all the highlighted yellow and red elements too? And some of them will just have a blank for the unit type column?

Sorry - just saw this. Yes! include the highlighted elements and blank for unit type.
