### ISSUE TITLE
User engagement analysis

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/cas-reporting#182]
Now that's we've finished our user engagement, what did we learn and what can we share?

- [x] Complete analysis of user feedback
- [x] Rollup of feedback
- [x] Share out

**Comment by patriciarussellCAS** [comment]
Hey @NicoleGovvy - anything left to do on this or do you think it's almost good to close? Thanks!

**Comment by NicoleGovvy** [comment]
@patriciarussellCAS I think just sharing the findings then we're good. This can be a small group - I might even just post in the Giraffe design chat.

**Comment by NicoleGovvy** [comment]
**Business area follow-up**

- Advanced guidance/notice if possible for changes to help operators with setting up their own systems/spreadsheets to get ready for reporting

**Features we have tickets for OR are in the user story map**

- Download in-progress/submitted reports in multiple formats (#144, #149)
- View historical reports (I swear this has a ticket but can't find it)
- Bulk upload feature (#133)
- Would like ability to view/download before submitting #144, #201)
- See completion status (#186)
- Version history table for operators: see date, name, reason (#178)
- View aggregate LFO summary for all facilities (#202)
- User story map, no ticket:
- Confirmation after submission via email
- Submit a correction to a report

**General opportunities (not feature-specific)**

- Clear terminology (site/facilities were being mixed up)
- Provide system guidance
- Auto-populate as much as possible

**Features for consideration**

- Submission notifications or correction requests: ability to designate who receives these or by default have these sent to the system users (not an executive)
- Transparency in calculations - have info on what the math is so it can be reproduced by the operator
- Ability to override calculations
- (post-post-post-post-post-post MVP) Ideally would like to select and compare multiple rows of data to each other (compare a specific year to another)
