### ISSUE TITLE
Prepare a plan for CPI Workshop in May

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-reporting#185]
#### Describe the task

Goose Team needs to come together to plan out our agenda for the CPI workshop that is happening in person. It will be a great opportunity to get some user feedback and test out our application.

#### Acceptance Criteria

- [ ] Goose sync to brainstorm on ideas and zero in on 2-3 directions
- [ ] Decide next steps

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by suhafa** [comment]
Ticket for CPI Workshop planning is here! @NicoleGovvy @zoeyli-46 @nanyangpro @patriciarussellCAS @hannahgov 
Do we have an idea of the timeline?

**Comment by patriciarussellCAS** [comment]
This has been cancelled.
