### ISSUE TITLE
Industry Reporter: Show Report Submission Status

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/cas-reporting#186]
As an Industry User
I want to see the submission status of my submission 
So that I can keep track of it's status

This would also help confirm for the user that their report has been submitted

**Comment by suhafa** [comment]
Mike flagged that we should probably get all the new statuses from the get go (especially for supplementary reporting parts). Statuses can also get complicated, there could end up being internal/external, LFOs can also make this tricky. It can be simplified, can we get confirmation on the list of statuses (started, submitted, rejected, incomplete, draft). 
- Map out statuses based on workflows

**Comment by patriciarussellCAS** [comment]
I believe this is capture in ticket #219 so will close this ticket.
