### ISSUE TITLE
Update activities table

### ISSUE THREAD

**Issue by mikevespi** [bcgov/cas-reporting#188]
#### Describe the task

As a part of the reporting process, the operators will have to inform us which activities take place in their facilities. The list of activities should be taken from the final redlined version of GGERR  schedule A tables 1 and 2. The lists of activities can be found in [this spreadsheet](https://bcgov.sharepoint.com/:x:/r/teams/00608-CPRInternal/Shared%20Documents/Carbon%20Pricing%20Transition%20SMEs/Registration%20App/Registration%20pt.%202%20Fields.xlsx?d=w8cf871009f8d43c19d1d79c69fa259e8&csf=1&web=1&e=I5V0hB), under the Dropdown Lists tab. The categories are separated into SFO and LFO activities. We will need to update the reporting_activities table to include boolean columns to indicate if an activity is an option for SFOs, and a column to indicate if it is available to LFOs. To begin with, we can assign all of the  SFO activities to also be available to LFO's, though need to confirm with BA which of them an LFO would not report on. By contrast, the LFO activities are not available to be carried out by SFOs. 

#### Acceptance Criteria

- [ ] Current list of activities in the reporting_activities table is up to date with the spreadsheet from BA
- [ ] Boolean column to capture whether it is an activity that SFOs can report on (initially set to true
- [ ] Boolean column to capture whether it is an activity that LFOs can report on
- [ ] Activities in the table all have the appropriate values for the two new columns above populated based on the spreadsheet

#### Additional context

- Reference Registration Part 2 data fields to confirm where data should be pulled from registration: https://bcgov.sharepoint.com/:x:/r/teams/00608-CPRInternal/Shared%20Documents/Carbon%20Pricing%20Transition%20SMEs/Registration%20App/Registration%20pt.%202%20Fields.xlsx?d=w8cf871009f8d43c19d1d79c69fa259e8&csf=1&web=1&e=I5V0hB

**Comment by pbastia** [comment]
@dleard @andrea-williams @mikevespi which schema should we put the program data on? I'm thinking we might want to create a separate one for it

**Comment by mikevespi** [comment]
From API refinement meeting: The activities table already exists from work done in registration, with data in it. Need to verify if the data is complete and up to date.

**Comment by patriciarussellCAS** [comment]
From Dylan: Table already created but activities list is outdated. Ballard to confirm the list from Registration.

**Comment by mikevespi** [comment]
Closing the loop here, I just posted in the SME channel to confirm that there are SFO activities that LFOs would not report on. If that is the case I have asked them to update the spreadsheet to represent which ones. If that hasn't happened / been answered by the time this is otherwise complete, just assign "true" to all of the activities LFO field, and we can true up the outliers as soon as that is done. If the answer to that quetsion turns out to be no, and that all SFO activities can be selected by LFOs, we will update this card to only require one new boolean field to represent the LFO only fields.

**Comment by mikevespi** [comment]
Closing this as the model made by registration captures distinction between the LFO SFO and mutual activities. I will go through the existing list in production to make sure it is up to date with the spreadsheet from BA, and if it is not I will create a new card to capture the work of updating it.

CC @BallardRobinett
