### ISSUE TITLE
Add a source type table

### ISSUE THREAD

**Issue by mikevespi** [bcgov/cas-reporting#189]
#### Describe the task

Part of reporting involves operators entering their source types. The source types can be found in tables 1 and 2 of Schedule A of [GGERR](https://bcgov.sharepoint.com/:w:/r/teams/00608-CPRInternal/Shared%20Documents/Carbon%20Pricing%20Transition%20SMEs/Reporting%20App/GGERR%20-%20FINAL%20Redline%20.docx?d=wa16b506f19524f2cafb6d699dc6f5d1a&csf=1&web=1&e=fqpYgc) and ** should be confirmed with business area **. 

#### Acceptance Criteria

- [x] Current list of source types confirmed with business area
- [x] A `source_type` table exists, in the same schema as the activities (#188) 
- [x] each source type with a unique ID

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by BallardRobinett** [comment]
I'm on the very last step of manually adding in the data for individual source types now and I ran into a handful of questions probably for business area or maybe @patriciarussellCAS 

1. Should I remove duplicates (source types with the same name for different reporting activities)
2. Should I fix style inconsistencies (punctuation, capitalization)
3. Are lines that have a strike drawn through them no intended to be included?
4. Is there a source that the ID for each source type should match, or are generated UUIDs appropriate?
5. What to put in the description field? (Its included in the AC)
6. There is a gas type associated with each source type. I want to confirm that no information about this is wanted in the table.

**Comment by BallardRobinett** [comment]
removing description field from the AC per our discussion in standup

**Comment by patriciarussellCAS** [comment]
Thanks @BallardRobinett - I'll work on getting those questions answered for you asap!
