### ISSUE TITLE
Reporting user research & Registration usability testing plan

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/cas-reporting#19]
#### Describe the task
Let's create a high-level research plan for reporting research and usability testing to guide OBPS report research and OBPS registration usability testing.

**Acceptance Criteria**
- [x] Create board or frame for planning
- [x] Determine research goals, usability testing goals, timeframe, approach (logistics, methods), high-level questions, etc.
- [x] Share with UX team members
- [x] Input from POs
- [x] Input from business area 

**Goal of ticket:** 
Get ready for external user research in late fall!

**Comment by NicoleGovvy** [comment]
@nanyangpro I've added a bit about usability testing here - starting with the user goals for testing should help us figure out what environment we'll need. We can get more granular if needed too.

**Comment by nanyangpro** [comment]
Amazing, thanks @NicoleGovvy!

**Comment by nanyangpro** [comment]
Added Moose tag so that @suhafa is aware and in the loop. :)
