### ISSUE TITLE
Frontend component tests for reporting app

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-reporting#190]
#### Describe the task

We need frontend component testing

#### Acceptance Criteria

- [x] decision between jest and vitest: vitest https://vitest.dev/
- [x] tests are enabled
- [x] tests allow `jsx` syntax
- [x] tests can be run with the `nx` tooling ([docs](https://nx.dev/nx-api/jest))
- [x] tests are run as part of CI
- [x] there is at least one test

**Comment by joshgamache** [comment]
Per discussion during Dev Team Agreements on March 27 (see Miro board), we're going to use Vitest in place of Jest. Nx already has [Vitest support](https://nx.dev/nx-api/vite/documents/overview), so the integration should be straightforward. [Further reference](https://nextjs.org/docs/app/building-your-application/testing/vitest)
