### ISSUE TITLE
Isolate Giraffe code from Moose production deployments

### ISSUE THREAD

**Issue by mikevespi** [bcgov/cas-reporting#192]
#### Describe the task

Once `giraffe-develop` has been merged into `develop`, we will need to ensure that the Registration and Reporting apps, as well as the API, can all be deployed independantly. If we do not, then then Registration release / deploy process will also deploy Reporting code that may not be production ready. This would expose unfinished work to the end users.

#### Acceptance Criteria

- [ ] Plan for synchronizing API releases
- [ ] Isolated release and deployment processes for each app (Reg., Rep., API)
- [ ] Documentation on decisions and processes

#### Additional context

We will want to ensure that members of both teams have an understanding of the approach taken.

**Comment by pbastia** [comment]
@patriciarussellCAS we might want to schedule this this coming sprint?

**Comment by rdromey** [comment]
Irrelevant based on work already completed.
