### ISSUE TITLE
Reporting Dashboard: Report Due Date Displayed for Users

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-reporting#193]
#### Description:

As an Industry Reporter, I want to see the due date for the annual report so that I am reminded of the deadline for submission. 

This work involves showing the users when their Annual Reports are due for the current reporting cycle. 
For example, 2024 Annual Reports will be due on May 31 2025. 
We need a way to show this "due date" on the Reporting Dashboard. 

[Wireframe](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=7789-2031&t=I6iDNx89Ts20WRNT-4)

#### Acceptance Criteria:

Given that I am an Industry Reporter
When I am in the BCIERS system
Then I want a clear visual to indicate when my annual report is due

Given that I am an Industry Report
When I am on the Reporting Dashboard for the current reporting year
Then I want to see the "report due date" on the page. 

#### Development Checklist:

- [ ] The text "Report Due [date]" appears above the grid matching the wireframe.
- [ ] The date is in [month] [day], [year] format
- [ ] "report_due_date" datetime column in the reporting_year table
- [ ] Due date value taken from reporting_year table
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [ ] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [x] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by patriciarussellCAS** [comment]
@suhafa curious what you're envisioning for this ticket. Is something sent to users (i.e. a notification) or is just information displayed on the app? something else? Let's chat!

**Comment by rdromey** [comment]
@BallardRobinett to write dev checklist

**Comment by patriciarussellCAS** [comment]
Reviewed and confirmed at this URL: https://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/reporting/operations

Could a Dev please confirm that the Dev checklist is complete? 
For example: 

- [ ] 'The text "Report Due [date]" appears above the grid matching the wireframe'. <-I don't see the date (even empty) included. Should I see "Report Due [date]" on the page? 
- [ ] 'Due date value taken from reporting_year table' <- is this correct? Given that the due date will always be May 31 of the year following the reporting year, where should we take this value from? 

Tagging Devs: @pbastia @dleard @joshgamache @ayeshmcg

**Comment by patriciarussellCAS** [comment]
I can confirm those issues were resolved but will add to our design backlog to capture the too-long/ugly timestamp for the due date.
