### ISSUE TITLE
As an Industry Reporter, I want a step to review my Operation information so that it is accurate for the current report

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-reporting#196]
#### Description:

Derived from reporting user story miro board. Users will come in the Reporting module and need to confirm that their operation information (for reporting purposes) are accurate. This information will get pulled from Registration but will be editable to match what is required for the reporting year. 

[Figma Design](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?node-id=7845-20996&t=PbPFizQUt87Ow0v4-0)

#### Acceptance Criteria:

Given I am a Industry Reporter on the Reporting Dashboard page
When I click on "Start" for an Operation's report
Then I am taken to the "Review Operation Information" page. 

Given I am a reporter
When I am confirming my operation information
Then I can make edits to the information presented

Given I am a reporter
When I am confirming my operation information
Then I can save the changes using the save button (without impacting the original data in registration!)

Given I am a reporter
When I am satisfied with the operation data
Then I can click confirm, my data is saved and I am directed to the next step (confirm facility data)

#### Development Checklist:

- [ ] an operation information page is the first step when starting / editing a report
- [ ] the operation data is stored in a report_operation table, separate from the operation table & specific to the report
- [ ] the report_operation table has a foreign key to the report table
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by patriciarussellCAS** [comment]
Display, refresh, edit - need API tickets for this. This snapshot should pull ALL required fields from Registration for reporting, even though  there are two "pages" or "steps" here (review operation and then review facility data). #195

**Comment by suhafa** [comment]
Tagging @mikevespi @pbastia to review or create any suitable API tix!

**Comment by pbastia** [comment]
~@suhafa @patriciarussellCAS @mikevespi  https://github.com/bcgov/cas-reporting/issues/243~ nevermind!

**Comment by patriciarussellCAS** [comment]
Could @pbastia  or @dleard review the AC we've written above. I think this card is refined but want to make sure Devs agree :)

**Comment by patriciarussellCAS** [comment]
@BallardRobinett can you confirm if this has already been started? If not we'll prep it for next sprint! thanks.

**Comment by BallardRobinett** [comment]
nope, has not been started by me

**Comment by pbastia** [comment]
@BallardRobinett we have an answer from @suhafa for the multi-select options: 
> It will be a multi-select, similar to this: https://mdbootstrap.com/docs/standard/extended/multiselect/ There are other instances where multi-select is required

mui has their own implementation: https://mui.com/material-ui/react-select/#checkmarks

**Comment by suhafa** [comment]
Needs designer review

**Comment by patriciarussellCAS** [comment]
https://[cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/reporting/operations](https://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/reporting/operations)
Table is there, but no records found.

**Comment by BallardRobinett** [comment]
URL for testing:

http://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/reporting/operations/[version_id]/review-operator-data

where [version_id] is the version id of the report you want to use

**Comment by patriciarussellCAS** [comment]
Thanks @BallardRobinett -what options are there for versions? *I think I figured it out (used version1)

**Comment by BallardRobinett** [comment]
Yeah I usually used version_id = 1 to test, after making a report using the API. That value is supposed to come from the previous page which lists all the users operations and has the option to start/continue a report

**Comment by suhafa** [comment]
Thanks for your work on this @BallardRobinett ! Nice to see our very first reporting form page :) Here are some design review notes:
1. The blue information blurb links back to registration, with the last word 'registration' as a hyperlink that takes you to your registration dashboard. Could we implement this at this point of time?
2. BORO ID and BCGHG ID are greyed out and meant to be auto-populated with information we will have on the user. It can't be edited. Can we visually reflect this? In Figma, we have #F2F2F2 (bc-background-grey) fill such fields
3. The button placement, stylization and sizing at the end are different than in Figma:
![Image](https://github.com/user-attachments/assets/d2b6385b-6df5-48f4-a231-4c74af4785f8)
Here is the same in Figma:
![Image](https://github.com/user-attachments/assets/65d435e3-bc1a-4a35-aa94-9ce7254ed76d)
4. I wasn't able to test out whether Reporting Activities, Regulated Products, Operation representative were multi-select drop-downs where we can select more than one entry
5. The header of the form looks different than what we have in Figma. I do believe we have this styled component we can borrow from Moose

![Image](https://github.com/user-attachments/assets/e6d0d0f2-1743-45af-8c4f-24b294042910)

**Comment by patriciarussellCAS** [comment]
I have created a follow-up design review ticket for this, so will close this issue.
