### ISSUE TITLE
Create recruitment list for OBPS research/testing

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/cas-reporting#20]
####Goal of Ticket
Have a list of vetted users to reach out to for OBPS reporting research and registration testing engagement using the criteria we established for users.

#### Describe the task

Have a list of vetted users to reach out to for OBPS reporting research and registration testing engagement.

#### Acceptance Criteria

- [x] (Hopefully) create list of users who indicated interest at Sept. 21 workshop
- [x] Cross-reference with Nan's list from past workshop (in the Nan's Notes Miro board)
- [x] Identify criteria gaps from list
- [x] Determine what gaps we need to fill
- [x] Identify (with business area?) how we can fill gaps
- [x] Fill gaps to have complete list
- [x] Business area review of identified users
- [x] PO review of identified users

**Comment by nanyangpro** [comment]
Added Moose tag so that @suhafa is aware and in the loop. :)

**Comment by NicoleGovvy** [comment]
This can be closed - we may have additional users we need to find or add in based on responses, but overall this is complete.
