### ISSUE TITLE
As an Industry Reporter I want to review and confirm my emissions and compliance report subtotals/totals so that they are accurate

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-reporting#201]
#### Description:

Derived from Reporting User Story Mapping Miro Board

#### Acceptance Criteria:

Given
When
Then

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by suhafa** [comment]
Patricia: "Might need to review this one. I assume they will review all their subtotals at the "Annual Report Section 2" as that's where they see all their totals. "

**Comment by patriciarussellCAS** [comment]
@suhafa would you agree that this step will occur via the emissions summary page and the compliance summary page? 
Or do we think there needs to be a more explict "review" step? This isn't really captured in our current wireframes, so I may icebox or close this ticket.

**Comment by suhafa** [comment]
@patriciarussellCAS it will occur via the emissions summary/compliance summary pages, so a 'review' step may be redundant. Feel free to close this ticket if nothing else comes to mind @patriciarussellCAS
