### ISSUE TITLE
Annual Report - Production Data Page

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-reporting#203]
#### Description:

As an Regulated Operation Reporter, I want to add production information so that I can fill out my compliance report

Regulated Operations (which includes Regulated Operations, Opt-ins, New Entrants) will need to fill out the Production Data form as part of their compliance report. 
This step happens at the facility level, after the user has filled out all the required emissions report data and viewed their emissions summary page. 
So for LFOs each facility will need to fill out a Production Data form. 
SFOs will only see this form once. 

Reporting-only Operations, Simple reports and EIOs do NOT fill out this production data form. 

[Wireframe here](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=8354-5937&t=bYuJTA82B6EqJ2TV-4)

#### Acceptance Criteria:

Given I am an SFO or LFO Regulated Operation 
When I click continue on the Emissions Summary Page
Then I am sent to the Production Data page (see wireframe link above)

Given I am an LFO Regulated Operation 
I need to see a list of regulated products that I previously selected in Registration on the top of the page, and I should be able to select products that apply to the particular facility so that I can enter appropriate data for each selected product only. 

Given I am an SFO Regulated Operation 
I need to see my regulated products that I previously selected in Registration expanded into fields, and their checkboxes are visible and clickable so that I can enter appropriate data for each pre-selected product, but also deselect if a product is not relevant for me at the time of reporting. 

Given I am an SFO or LFO Regulated Operation on the Production Data page and my products are selected
I need to fill out the required data fields for each products so that I can click on Continue and proceed to the next page: Allocation of Emissions. 

Given I am an LFO Regulated Operation
I have to fill out a new production data page for each facility. 

Given I am an LFO or SFO Regulated Operation
I need to ability to de-select products on the Production data page, as not all products are relevant for each facility in my operation. 

report_product model:
id pk
facility_report_id fkey->facility_report
unit varchar
annual_production numeric
production_data_apr_dec numeric
production_methodology varchar
storage_quantity_start_of_period numeric
storage_quantity_end_of_period numeric
quantity_sold_during_period numeric
quantity_throughput_during_period numeric

#### Development Checklist:

- [x] Add a report_product model to the database as above
- [x] Add a production data page at /reports/{version}/facilities/{facility_id}/production-data
- [x] The production page pulls the list of products selected from operation_regulated_products
- [x] The production page pulls the operation type & conditionally displays product selections as described in the AC
- [x] If operation type is LFO, products can be selected/deselected
- [x] Production data is saved to the report_product table on continue/save
- [x] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by patriciarussellCAS** [comment]
TO CONFIRM: Should we only give LFO's the option to select and de-select Products on this page? 
Given that an SFO must identify their regulated products in Registration, and they only have 1 facility, all regulated products selected in registration would apply and need to be selected on the Production Data page. If they need to make changes to their list of products, should they be forced to go back and update this in registration? Or should they be allowed to do that here? My thoughts are they they should NOT be able to change products here. Thoughts from others? 
tagging: @suhafa @pbastia @dleard and @andrea-williams for visibility

**Comment by suhafa** [comment]
@patriciarussellCAS after our collab session, I went in and undid the decision to hide SFO's products' checklist and updated the AC for it. It will be visible and un-selectable for both as it remains unknown how well registration and reporting will sync for this piece. Do let me know if it isn't the case!

**Comment by patriciarussellCAS** [comment]
hey @pbastia is there a direct link to this so I can review? Or should I go through the whole reporting workflow to get there?

**Comment by pbastia** [comment]
@patriciarussellCAS you can go the whole workflow! Otherwise this works too: https://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/reporting/reports/2/facilities/f486f2fb-62ed-438d-bb3e-0819b51e3aff/production-data

**Comment by patriciarussellCAS** [comment]
Thanks @pbastia! Here are my review notes based on what's not consistent with the wireframes: 

1. Production Methodology should be a dropdown menu with 2 options: OBPS Calculator or "other"
> If they select "other" there needs to be a description box for them to add the details 
2. Production Methodology should be called "Production Quantification Methodology"
3. the second "quantity of storage" listed should say "at the END of the compliance period [Dec 31]" but current says at the beginning. 

Thanks.

**Comment by patriciarussellCAS** [comment]
@pbastia the link above is giving me an error. Is there a new URL I could try? I still can't get past the "person responsible" page so need a direct link to review.

**Comment by patriciarussellCAS** [comment]
Here's the full link:  https://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/reporting/reports/1/facilities/f486f2fb-62ed-438d-bb3e-0819b51e3aff/production-data

**Comment by vesselak** [comment]
Comments from previous test are now addressed and therefore accepting ticket.

Previous notes that informed testing: 
Production Methodology should be a dropdown menu with 2 options: OBPS Calculator or "other"
If they select "other" there needs to be a description box for them to add the details

Production Methodology should be called "Production Quantification Methodology"
the second "quantity of storage" listed should say "at the END of the compliance period [Dec 31]" but current says at the beginning.
