### ISSUE TITLE
Compliance Summary: Emissions allocation data to be auto-populated in compliance summary

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-reporting#204]
#### Description:

As a Regulated Operation Reporter, I want my emissions allocation data from the Allocation of Emissions page to be auto-populated in the compliance summary report so that I can review it as part of compliance, 

#### Acceptance Criteria:

Given
When
Then

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by patriciarussellCAS** [comment]
Is this is relevant?

**Comment by suhafa** [comment]
@patriciarussellCAS I think so, it is for capturing the dependency between the Allocation of Emissions page and Compliance Summary. More back-end-y stuff I imagine though, about how we feed in the data from Allocation of Emissions into Compliance. A dev can determine if we need separated out tickets like this of various screens feeding into Compliance Summary, or is one catch-all ticket enough though! @dleard @pbastia
