### ISSUE TITLE
Production Data: Additional Production info for Q1 of 2024

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-reporting#205]
#### Description:
"As a Regulated Operations Reporter, I want to enter additional Production info for Q1 of 2024"

Derived from Reporting User Story Map from Miro. See #14 for context

This is included already in the Production Data [Wireframe](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=8354-5937&t=o8adu9sN3N9g101Z-4)

#### Acceptance Criteria:

Given
When
Then

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by patriciarussellCAS** [comment]
Note - since these additional fields are already captured in the wireframe, I don't think we need a separate ticket for this. 
We may need a follow-up ticket for the 2025 reporting year to remove this data field, or hide it. 
Could this be repurposed for regulated operations who become regulated part-way through a year and need to provide partial year data?

**Comment by patriciarussellCAS** [comment]
Already captured in Production Data form. Closing ticket.
