### ISSUE TITLE
Partial-year Reporting Page: Becoming Regulated part-way through the year

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-reporting#206]
#### Description:

As a Regulated Operation reporter who becomes regulated part-way through the year I need additional fields so that I can report additional emissions and production amounts, as well as certain dates

[Wireframe](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=14002-2013&t=VMT3IlB4hx34NGTB-4)
Designer needs to first confirm the the flow of this report type. 

#### Designer tasks

- [x] Review and confirm the wireframe 
- [x] Document additional information about regulated partial year operation reports from BA
- [x] Create designs or a separate flow
- [x] See what impacts registration or is affected by registration
- [x] Review and refine with BA

#### Notes:

- Future dev ticket AC: 
Given that I am an Industrial Reporter who becomes regulated part-way through a reporting year
When I fill out my annual report
Then I need to fill out an additional page with partial year data so that I can fulfill my reporting obligation.

**Comment by rdromey** [comment]
Splitting out dev checklist into its own ticket

**Comment by suhafa** [comment]
The [design work is completed](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=14002-2013&t=oB3Uq9Ir2mu0utaD-1) however, note the following for future iterations:
- BA to look at how dates would be different for partial year things
- BA to confirm with legal if we need two instances of Compliance summary
- Need to update the Emissions Categories page as it will be different across all pages

[Notes for these are here](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=16076-3150&t=oB3Uq9Ir2mu0utaD-1)
