### ISSUE TITLE
Industry Reporter: Annual Report Sign-off

### ISSUE THREAD

**Issue by patriciarussellCAS** [bcgov/cas-reporting#207]
#### Description:

As an Industry Reporter I want mandatory checkboxes to confirm that I believe the data to be accurate and complete, so that I can official sign-off on the Report Submission.  This will be in the final step of reporting under 'Sign-off and submit'. If the user doesn't select all of these boxes they should not be allowed to submit the report. 

[Wireframe here](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=15566-2626&t=y5J53MqdJClCog9N-1)

It will also have a field that requires the name of of the signer, and potentially (to be confirmed) the date of signing. We should consider having validation that disallows users from entering numbers and special characters

#### Acceptance Criteria:

Given I am an Industrial Reporter
When I have completed the annual reporting process
Then I need to sign-off/acknowledge that the report is complete and accurate before hitting submit

#### Development Checklist:

- [x] Frontend webpage is built to match design wireframe.
- [x] URL matches document in docs/reporting/url-patterns.md
- [x] 'Sign-off and submit' button is only clickable when all mandatory checkboxes are checked.
- [x] Disallow special characters and numbers in the Signing field
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by rdromey** [comment]
@BallardRobinett to finish AC/Dev Checklist

**Comment by ayeshmcg** [comment]
For testing:
https://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/reporting/reports/1/sign-off
