### ISSUE TITLE
Additional Reporting Data Page: Regulated Operations and Reporting-only Operations 

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-reporting#208]
#### Description:
As a Regulated Operation, I want to add additional data so that I can fill out my emissions and compliance report
As a Reporting Operation, I want to add additional data so that I can fill out my emissions report, and need to ensure that "electricity generated" is an optional field only. 

This page is required for all Regulated Operations (including Opt-ins and New Entrants) & Reporting Operations. 
It does NOT apply for EIOs or Simple Reports. 
The emissions and compliance reports are done at the facility level, but there are a couple of data fields that we need to ask users for at the operation level. 
For SFOs this won't make a difference, and will just be an additional page after emissions and compliance data. 
For LFOs they would see this page after they have completed all the facility level emissions and compliance forms.

[Wireframe](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=11194-2331&t=eSSAIGWBakSJByjT-4)

#### Acceptance Criteria:

Given that I am a Regulated operation
When I've completed all the facility-level reports (emissions and production)
Then I need a form to fill in additional information

Given that I am a Reporting Operation
When I've completed all the facility-level reports (emissions only)
Then I need a form to fill in additional information, 

#### Development Checklist:

- [x] Add a model report_additional_data to store the additional fields required for Regulated and Reporting Operations. This will track the extra data added at the operation level.
- [x] Add an additional reporting data  page at /reports/{version}/additional-reporting-data
- [x] Additional reporting data is saved to the report_additional_data table on continue/save
- [x] Form for capturing emission should be rendered only if user clicks on yes for **Did you capture emissions?**
- [x] Electricity generated field should only be visible if operation's regisration purpose is Reporting Operation only.
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

- We have separate tickets for the "Additional Data" forms specific to a) New Entrants b) Regulated Partial Year

**Comment by patriciarussellCAS** [comment]
I took a stab at refining this but need to discuss at next week's refinement with everyone/

**Comment by rdromey** [comment]
@ayeshmcg to write dev checklist

**Comment by ayeshmcg** [comment]
To test:
1.  Go to https://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/reporting/reports, and select and operation, and it url after the report version(number) add 'additional-reporting-data' like https://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/reporting/reports/1/additional-reporting-data

2. To test electricity generated fiedl, select operation 17 from reports page and go to additional-reporting-data

**Comment by patriciarussellCAS** [comment]
Hey @ayeshmcg I'm getting an error trying to get through Operation 17's workflow to this page. May need some assistance to review this.

**Comment by ayeshmcg** [comment]
@patriciarussellCAS 
Can we schedule a call to check this together?

**Comment by patriciarussellCAS** [comment]
Follow-up notes: 

- I will confirm with BA whether regulated operations should see "electricity generation"
- Need a design/tech debt ticket to move electricity generation into it's own field below under "Additional Data" that matches the wireframe.

**Comment by ayeshmcg** [comment]
@patriciarussellCAS 
Created this tech debt card - https://github.com/bcgov/cas-reporting/issues/372

**Comment by patriciarussellCAS** [comment]
Confirmed that Regulated Operations see electricity generated, and Reporting Operations do NOT. I've added this to the tech debt card as well.
