### ISSUE TITLE
Scheduling OBPS research/testing sessions

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/cas-reporting#21]
####Goal of Ticket
Plan logistics of OBPS reporting research and registration usability sessions.

#### Describe the task
Have a plan to manage logistics for OBPS research/testing.

**Acceptance Criteria**
- [x] Create [tracking spreadsheet](https://bcgov.sharepoint.com/:x:/r/teams/00608-ScrumTeam/Shared%20Documents/Scrum%20Team/OBPS/Interview%20Notes%20%26%20Recordings/UserEngagement-Tracking.xlsx?d=wda1afef4c2bd42278fc4bed1203f1572&csf=1&web=1&e=h6VbnO)
- [x] Write outreach email to potential research participants
- [x] Look into Calendly as a scheduling option
- [x] Contact identified operator staff to recruit
- [x] Schedule & track sessions as they are booked

**Comment by NicoleGovvy** [comment]
https://bcgov.sharepoint.com/:x:/r/teams/00608-ScrumTeam/Shared%20Documents/Scrum%20Team/OBPS/Interview%20Notes%20%26%20Recordings/UserEngagement-Tracking.xlsx?d=wda1afef4c2bd42278fc4bed1203f1572&csf=1&web=1&e=h6VbnO

**Comment by patriciarussellCAS** [comment]
There will be future OBPS test sessions, however I'll close this one for now as it's complete and we can create new tickets when needed
