### ISSUE TITLE
Prepare for usability testing for feedback on wireframes

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-reporting#211]
#### Describe the task

Let's do a quick and short usability testing session to validate our wireframes prior to development with a small group of users (4-5, more if there is interest)

#### Acceptance Criteria

- [x] Confirm users
- [x] Plan the session
- [x] Create usability script
- [x] Confirm script/questions for users with Business Area
- [x] Prepare invites to send users to books sessions
- [x] Set up CHEFS for consent form
- [x] Create prototypes
- [x] Send invites

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by suhafa** [comment]
ticket for usability testing is here @patriciarussellCAS !

**Comment by suhafa** [comment]
Based on discussion with Patricia, we can push this off until guidance docs are sent out to industry. Follow up with the business area on when that is

**Comment by suhafa** [comment]
Will be reviewing prototypes with BA for finalization. Have to set up Calendly and send out invites.

**Comment by patriciarussellCAS** [comment]
Invites sent and sessions set up :)
