### ISSUE TITLE
As an Industry Reporter, I want to access my reporting dashboard so that I can view my operations to submit reports

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-reporting#213]
#### Description:

Following the work in #194 , we want an environment for Reporting where the reporting table lives based off the wireframes. 
In the table the user can see their operation name and other details that assist them to start submitting & viewing reports. They can also branch off to see past submissions, analytics etc. 

[Wireframe here](https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=7789%3A2031&mode=design&t=mcPbilWJY8esC5XQ-1)

#### Acceptance Criteria:

Given
When
Then

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by suhafa** [comment]
@patriciarussellCAS Reporting dashboard ticket here!

**Comment by rdromey** [comment]
To be broken out to developer tickets by @mikevespi

**Comment by mikevespi** [comment]
@suhafa are the fields of the table confirmed? And if so, how will we represent Operations no longer owned? e.g. If I sell an operation in 2024 and it's now 2026, how is that represented? 

If this is the path to old reports as well I feel like the status might make that a little unclear, as it  visually represents this reporting year.

**Comment by rdromey** [comment]
Broken out into cards 217 - 221 plus one more card for styling. Also going to create an epic related to this discussion.
