### ISSUE TITLE
Create design guidelines for devs

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-reporting#222]
**Describe the task**
Devs need UI guidelines on how to stylize the components, and share this work across both teams.

**Acceptance Criteria**

- [x] Sync with Nan to identify some common components 
- [x] Sync with Nan to make some designs consistent (forms, dashboard tiles) + discuss how to implement changes
- [x] Sync with Nan to finalize a dashboard design
Make a draft design guideline: 
- [x] Forms
- [x] dashboard(s)
- [ ] activities
- [x] Conduct a dev/design sync to walk devs through the guideline and get their feedback 

**Additional context**
For future work, designers can create components that align with the design guideline

**Comment by suhafa** [comment]
@nanyangpro tagging you here for your reference!

**Comment by suhafa** [comment]
Synced with Nan, I will be fleshing out Form designs + Common Dashboard components as well.

**Comment by suhafa** [comment]
Activities design and form design needs to be detailed in the guidelines

**Comment by suhafa** [comment]
Created #261 for capturing future design guideline work, since it is not a priority currently. Guidelines have been updated for others. Can be closed

**Comment by patriciarussellCAS** [comment]
Thanks Suha - have you done a walk through with devs? Is that still needed? 
Could you share the link with me so I can review it again as well? I think it's been a while.

**Comment by suhafa** [comment]
Hi @patriciarussellCAS! Yes devs from Team Moose have reviewed the guidelines and continue to reach out for further details. I didn't do a dev/design sync though as I didn't feel the need for it after reviewing it one on one with the few who are implementing the guideline. We could do a more elaborate one for Giraffe when we have UI for the reporting forms. 
The [link for Design Guidelines can be accessed here](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=9844-2039&t=CA1EEkDA4ORvaJP8-1)
