### ISSUE TITLE
Take screenshots of SWRS/SWIM

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-reporting#23]
Let's get some screenshots for reference!

**Acceptance Criteria:**
- [ ] Make a space in Miro to keep these screenshots
- [x] Get access to SWRS/SWIM
- [ ] Go through and take screenshots of the screens!
- [ ] Put screenshots in Miro
- [ ] Add any comments/questions in Miro
- [ ] Share with project team

**Goal of this ticket:**
- Be able to easily pull up SWRS screens for reference to compare to our reporting system/CIIP

**Comment by jaimiebutton** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Giraffe-Sprint-Board-64597698d333490011486ab9/issues/bcgov/cas-reporting/23?planning-poker) with Zenhub @NicoleGovvy

**Comment by patriciarussellCAS** [comment]
@NicoleGovvy - do we still need this ticket?

**Comment by patriciarussellCAS** [comment]
https://bcgov.sharepoint.com/:b:/r/teams/00608-CPRInternal/Shared%20Documents/Carbon%20Pricing%20Transition%20SMEs/Reporting%20App/SWRS%20ReportPreview.pdf?csf=1&web=1&e=Hcyn4y
