### ISSUE TITLE
As an industry reporter, I want to see an overview of all the major sections of my report

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-reporting#236]
#### Description:

When the user has started reporting, we want to see an overview step breakdown. We have implemented this design in registration so this ticket may involve pulling that component for reporting as well. This component exists in the **Registration Module - External BORO ID application** forms

<img width="1043" alt="image" src="https://github.com/bcgov/cas-reporting/assets/99216375/cf4d4d66-b123-4e5d-8836-b24d675eebf4">

#### Acceptance Criteria:

Given I am an industrial reporter
When I start a new report for the current reporting year
Then I see an overview on top of the page
And it has links to the different sections of the report

#### Development Checklist:

- [x] One shared frontend component from the similar one in registration app- we can reuse te
- [x] Takes as a prop: a list of (title, link) tuples and a 'selected index'
- [x] Add this to the top of a 'new report' page
- [x] Links currently don't point anywhere, and the titles are the ones on the screenshot
- [x] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
Refinement May 21st:
2 pieces of functionality:
- the component takes a list of steps (text)
- the component takes a highlighted step (probably a flag)

**Comment by patriciarussellCAS** [comment]
Hey @pbastia  and @suhafa - this ticket looks refined to me. Would you agree?

**Comment by pbastia** [comment]
@patriciarussellCAS agreed!

**Comment by patriciarussellCAS** [comment]
@suhafa just flagging that the visual in this ticket is outdated.

**Comment by suhafa** [comment]
@patriciarussellCAS updated, thanks for flagging!

**Comment by ayeshmcg** [comment]
@patriciarussellCAS 
The component used in regisrtation for header, can be reused and it can be used under reporting in the same way
![image](https://github.com/bcgov/cas-reporting/assets/171871432/73343869-ac4b-4207-b734-78ae2b9dbb4d)

**Comment by suhafa** [comment]
**Design review:**
1) The 'yellow' selected component needs to have its text in black within the cirlce, not white, as it fails contrast and accessibility standards (important)
2) The blue circles have to have the color '#38598A' (not as important)

I wasn't able to confirm the functionality by clicking through the entire component, and can note the above based on the screenshot @ayeshmcg attached. fyi - @patriciarussellCAS

**Comment by pbastia** [comment]
There are a few design issues to fix, back to the sprint backlog :) 
@ayeshmcg @patriciarussellCAS

**Comment by ayeshmcg** [comment]
@pbastia
Added a report page with multistep header, form will be added later when we have schema. 

@suhafa 
Added the changes you mentioned
![image](https://github.com/bcgov/cas-reporting/assets/171871432/afa4c5f6-3c6a-4fc3-b349-99946f66f83b)

**Comment by suhafa** [comment]
Looks great @ayeshmcg thanks for working on this!

**Comment by patriciarussellCAS** [comment]
https://[cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/reporting/report](https://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/reporting/report)
