### ISSUE TITLE
Current reporting year on the reporting dashboard 

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-reporting#238]
#### Description:
As an Industry Reporter I want to see the current reporting year on my reporting dashboard so that I am aware which year I am preparing and submitting reports for. 

This work involves showing the current reporting period on the reporting dashboard. The title of the Reporting dashboard will display the reporting year (the calendar year for which they are reporting for). 
 
![Image](https://github.com/bcgov/cas-reporting/assets/99216375/1553bc2d-84e5-45af-a626-d92fe39488dc)

#### Acceptance Criteria:

Given that I am an Industrial Reporter
When I am in the Reporting module
Then I want a clear visual to indicate which reporting year I am working in

#### Development Checklist:

- [x] A "ReportingYearService" with a `get_current_year()` method to centralise the logic of how this is computed
- [x] The value for the reporting year should probably be grouped in the API call for the operation dashboard, if it makes sense (i.e. if we're not still using the registration method)
- [x] Calculation logic: Current reporting year is the latest reporting year with the "reporting_window_end" value passed
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by suhafa** [comment]
We have two needs here:
1) Knowing what the current reporting period is
2) What is the report due dates 

This ticket is for the former, and for the latter we have #193

**Comment by rdromey** [comment]
@pbastia  to add dev checklist

**Comment by patriciarussellCAS** [comment]
@suhafa design review

**Comment by joshgamache** [comment]
@suhafa @patriciarussellCAS 
Address for this on (when logged in) is `/reporting/operations`: [https://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/reporting/operations](https://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/reporting/operations).

You can also get here now directly from the root dashboard, under the Reporting card, via the _Submit Annual Report(s)_ link.

**Comment by patriciarussellCAS** [comment]
This URL doesn't work for me. I get this error: Application error: a client-side exception has occurred (see the browser console for more information).

Any thoughts?

**Comment by suhafa** [comment]
I am not able to access this either. Can this be mitigated by perhaps a loom video recording that demos it? I know you guys are doing some merge work so it may not be possible to view it ourselves?

**Comment by patriciarussellCAS** [comment]
I was able to confirm this now. 
Notes: 

- we'll need to fix the breadcrumbs for this page
- we'll need to update the title so "year" is capitalized (Reporting Year)
