### ISSUE TITLE
Conduct engagement sessions for reporting research + reg testing

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/cas-reporting#24]
#### Goal of Ticket
Complete engagement sessions with industry on reporting and registration.

#### Describe the task

Conduct usability testing & research as well as documenting session findings.

#### Acceptance Criteria

- [x] Conduct research/testing sessions on Tues, Oct 31
- [x] Conduct research/testing sessions on Wed, Nov 1
- [x] Conduct research/testing sessions on Thurs, Nov 2
- [x] Conduct research/testing sessions on Mon, Nov 6
- [x] Conduct research/testing sessions on Tues, Nov 7
- [x] Conduct research/testing sessions on Thurs, Nov 9
- [x] Conduct research/testing sessions on Wed, Nov 15
- [x] Document sessions for further analysis

**Comment by rdromey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Giraffe-Sprint-Board-64597698d333490011486ab9/issues/bcgov/cas-reporting/24?planning-poker) with Zenhub @NicoleGovvy @jaimiebutton
