### ISSUE TITLE
Research spike: Nx Cloud (and Replay?) fitting within Gov policy

### ISSUE THREAD

**Issue by joshgamache** [bcgov/cas-reporting#242]
## Description:

Nx Cloud _could_ be helpful in administering and analyzing our CI and Monorepo. This ticket aims to determine: 

1. If it's usage is possible within BCGovs guidelines. `TODO: What guidelines?` 
2. What benefits we would see. What downsides.
3. Assess it's impact if it were to go down.
4. Assess the impact/benefit of using Nx Replay (which requires Nx Cloud).

## Consideration and notes

- https://nx.dev/ci/intro/why-nx-cloud
- https://nx.dev/concepts/how-caching-works
- https://nx.dev/ci/features/remote-cache
- Couldn't easily find Nx's data/privicy policies, may need to contact for further details?

## **Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] ~~User story is included~~
- [ ] ~~User role and type are identified~~
- [ ] Acceptance criteria are included
- [ ] ~~Wireframes are included (if required)~~
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

## **Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

**Comment by dleard** [comment]
Not worth the effort, may not actually be useful to us at all. Closing
