### ISSUE TITLE
API endpoint for operation list on Reporting Dashboard page

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-reporting#243]
#### Description:

As a developer, I want to have an API endpoint to fetch all the data for the Operations table page, so that I can populate the page

Note: this endpoint does NOT handle pagination at this point

#### Acceptance Criteria:

Given I develop the front end page for the operations table for a particular user
When I want to fetch the data for the table 
Then I have access to an API endpoint returning all that data
And that endpoint is exposed on `/api/reporting/operations`

Given I call the API endpoint for the operations page
When I parse the data
Then it is in JSON format
And contains an array of objects with the data for the current reporting period

Data:
```
[
  {
    name: <string>,
    facility_count: <int>,
    report_id?: <id>
  },
..
]
```

#### Development Checklist:

- [x] A new API endpoint
- [x] ~Facility count is also pulled from registration data~ confirmed with @suhafa that this was not the case anymore
- [x] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Blocking
#234 
Add `report:id` if exists show continue, if none show start.

**Comment by patriciarussellCAS** [comment]
Hey @pbastia can you confirm that this ticket is related to the "Review Operation Information" page in reporting? Is it also impacting the "Reporting Dashboard" page, where we pull in Operation names? I just want to make sure I'm understanding the term "Operation table" and "Operation page" mentioned above correctly.

**Comment by pbastia** [comment]
@patriciarussellCAS this is related to the operations list page (#217) and is the API endpoint supporting it. For now we just use the registration one, which doesn't expose all the necessary information

**Comment by pbastia** [comment]
@Sepehr-Sobhani can we confirm the `v1` in the API path? I don't think this is part of a specific API version for now

**Comment by rdromey** [comment]
@pbastia to split out various tickets

**Comment by pbastia** [comment]
Development items were taken out and added to #234 and #219

**Comment by Sepehr-Sobhani** [comment]
> @Sepehr-Sobhani can we confirm the `v1` in the API path? I don't think this is part of a specific API version for now

We have been discussing the best approach for splitting our APIs and adding new features on top of existing ones. We have found that splitting routes into different folders is the best way with minimal changes to the codebase, rather than versioning the API itself. This approach allows us to separate routes based on different backend apps, and we don't have to refactor multiple frontend codes to separate the logic.
