### ISSUE TITLE
Refactor the frontend Layout component to be a shared component

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-reporting#252]
### Description of the Tech Debt

Right now @BallardRobinett is about to duplicate the file for the reporting app, and we need to make sure we only manage one layout component.

#### Tech Debt Triage

The purpose of our technical debt triage process is to analyze technical debt to determine risk level of the technical debt and the value in tackling that technical debt.

#### Risk Value Scoring:

| Level  | Value                 |
| ------ | --------------------- |
| High   | <div align="center">3 |
| Medium | <div align="center">2 |
| Low    | <div align="center">1 |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |       |       |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |       |       |
| System Fault Risk - Risk of system errors or application downtime                                                             |       |       |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |       |       |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |       |       |
| <div align="right">**TOTAL SCORE:**                                                                                           |       |       |

**Comment by pbastia** [comment]
@patriciarussellCAS @rdromey  highlighting this ticket as a follow-up to @BallardRobinett 's work on #217

**Comment by patriciarussellCAS** [comment]
@joshgamache is this still relevant?

**Comment by pbastia** [comment]
Looks like that component has been refactored at some point with the dashboard work. We can close this!
