### ISSUE TITLE
Conduct user testing sessions and compile feedback

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-reporting#260]
#### Describe the task

After preparing for usability testing in #211, we will conduct sessions with users and compile feedback and recommendations

#### Acceptance Criteria

- [x] Conduct session 1
- [x] Compile feedback
- [x] Conduct session 2
- [x] Compile feedback
- [x] Conduct session 3
- [x] Compile feedback
- [x] Conduct session 4
- [x] Compile feedback
- [x] Conduct session 5
- [x] Compile feedback
- [x] Conduct session 6
- [x] Compile feedback
- [ ] Conduct session 7
- [ ] Compile feedback
- [x] Consolidate all feedback

#### Additional context

Add any other context about the task here.

#### Definition of Ready:

Note: If any of the points are not applicable: delete or mark N/A

- [x] Topic is clearly Defined.
- [x] Task Description is Clear.
- [x] People to speak to are identified (if applicable).
- [ ] Acceptance Criteria is Clear.
- [x] Ticket Title is Clear.
- [x] Ticket is reasonably Split up/sized.
- [ ] Value/Pain is Clear.
- [ ] Relevant Team Members are assigned.
- [ ] Ticket Estimated.

#### Definition of Done.

Note: If any of the points are not applicable: delete or mark N/A

- [ ] Rough User Stories Proposed.
- [ ] Follow-up Tickets created (if necessary).
- [ ] Findings are documented (if necessary).
- [ ] Reference docs/spreadsheets identified and indexed.
- [ ] Value Proposition Canvas (if required)

**Comment by patriciarussellCAS** [comment]
@suhafa - I still haven't heard back from additional users. I suggest we close this ticket once the feedback is compiled and open a new ticket if we end up having more sessions next sprint.

**Comment by suhafa** [comment]
All feedback consolidated in Miro 'Usability Test Findings | June 2024'
