### ISSUE TITLE
Create design guidelines for activities and other reporting design element

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-reporting#261]
#### Describe the task

After #222 create design guidelines for the forms for reporting, for things like activities etc

#### Acceptance Criteria

- [x] Create draft design guidelines for activities
- [x] Sync with Dylan or other devs to confirm if there is anything else needed to be specified for the guidelines
- [x] Update it accordingly

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by suhafa** [comment]
The completed design guide [can be found here](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=11061-2994&t=1ViB6hZnlhdzxu7X-1), I expect minor tweaks to this as we go along and further elaboration. But the foundation of these scenarios is complete.

**Comment by patriciarussellCAS** [comment]
Thanks @suha! Looks great. I'll close this now, but note the guide will continue to evolve over time.
