### ISSUE TITLE
Activity page - Fuel Combustion by Mobile Combustion

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-reporting#271]
#### Description:

[Wireframe](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=8832-11845&t=MOAHRLo6VtMfTo55-4): 

Following #253 we have a full stack example of how to generate an activity emissions form using the API form builder service. The implementation here should be very similar to the GSC activity page.

Documentation on the full stack steps necessary to create an activity page are in our [docs](https://github.com/bcgov/cas-registration/tree/develop/docs/frontend)

Use the excel file (BCIERS Reporting Fields V2 in the SME channel files  - Reporting App directory) provided by IRC to determine what the necessary activity, source type, gas type, methodology, reporting fields & related configurations that need to be added are.

#### Acceptance Criteria:

Given I am on the mobile combustion activity form page
When I first land on the page
Then the activity schema is fetched & displayed

Given the schema has rendered correctly
When I make selections that have dependencies (gas type, methodology)
Then the correct options and fields as defined from the configuration are shown

#### Development Checklist:

- [x] Any activities, source types, gas types, methodologies or reporting fields needed for the configuration that are not already in the database are added
- [x] The configuration relationships have correctly been added to the database
- [x] The many to many reporting field data (if needed) has correctly been added to the database
- [x] The base schema for the activity & source types have been added to the database
- [x] A routing directory/page has been added to both the industry_user & industry_user_admin flows for the activity
- [x] A parent component (named for the activity) has been added to the components in the activity directory
- [x] The page fetches the correct initial activity schema from the API service on initial load
- [x] A uiSchema exists in the components/activities/uiSchema directory for the activity & source types (will move to the database eventually, but can live here for now)
- [x] Conditional fields render dynamically as data is entered
- [x] On selecting a source type (or if there is only one, on loading the page) The first set of data fields is displayed (defaultEmptySourceTypeState)
- [x] Matches the wireframe

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by patriciarussellCAS** [comment]
@dleard would you mind sharing the URL so I can review?

**Comment by dleard** [comment]
URL for this one is:
/reporting/reports/1/facilities/1/activities/fuel_combustion_by_mobile

**Comment by patriciarussellCAS** [comment]
Thanks! Tagging @suhafa for design review. 
My notes: 

- Fuel Name <- this should be a dropdown, correct? 
- If "Fuel Classification" is being imported from the regulation, should this also be a dropdown menu? 
- Would "Annual Fuel Amount" be the total of all 4 quarters? Or is this a different total? (*to confirm with BA)
- When gas type is selected, should methodology be at the top of the list? so it matches the order in the spreadsheet?

**Comment by suhafa** [comment]
Good points @patriciarussellCAS!

**Design review:**
1. We seem to be missing 'Fuel Units' here
2. Fuel Description is missing '(Optional)'
3. Emissions is missing '(tonnes)' in the field name at the end
4. Emissions Equivalent is missing '(tCO2e)' in the field name at the end

**Comment by patriciarussellCAS** [comment]
I've noted these design issues and will put them in a separate ticket. Then we can close this ticket.
