### ISSUE TITLE
Auth not working when deployed to OpenShift

### ISSUE THREAD

**Issue by joshgamache** [bcgov/cas-reporting#273]
#269 deployed the Dashboard, Registration (part 2) and Reporting applications to OpenShift. Login works, but Auth seems to have issues. The shared dashboard displays nothing beyond the header.  

## Acceptance criteria

- [x] Auth works.
  - [x] shared dashboard displays options.
  - [x] Registration 2/Reporting display pages behind auth.
- [x] Assets loaded by each application from the right location
   - Currently `/registration`, `/reporting` request _some_ assets from `address.com/_next` not `address.com/registration/_next`

**Comment by patriciarussellCAS** [comment]
Note: Some work being done related to this by Marcell in Moose.

**Comment by joshgamache** [comment]
~~https://github.com/bcgov/cas-registration/pull/1884 addresses multi-app routing. `withAuthorization` is addressed, which is a core piece of the Auth. There is a chance the changes there resolve this, I'll be monitoring it.~~
