### ISSUE TITLE
Reporting Dashboard: See 'Actions' column

### ISSUE THREAD

**Issue by BallardRobinett** [bcgov/cas-reporting#274]
#### Description:

As an Industry Reporter, I want to see an 'Actions' column in my operation table on the Reporting dashboard so I can start or continue my report. 

We need to let operators start or continue a report from the Reporting Dashboard page. For now this will link to a placeholder starting page for creating a report.

[Wireframe here](https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=7789%3A884&mode=design&t=cSGQYznXhtd4rwZd-1)

#### Acceptance Criteria:

Given that I am an external operator
And I view the operation list
Then the second to last column is labeled 'Actions'

Given that I am an external operator
And I view the operation list
If the operation has an existing report ID, it displays 'Continue'
Otherwise, it displays 'Start'

Given that I am an external operator
When I view the operation list
And I click on 'Continue'
I am taken to the review operation data page defined in #196 

Given that I am an external operator
When I view the operation list
And I click on 'Start'
Then I am taken to the review operation data page defined in #196 

Blocked: #196, #243 

#### Development Checklist:

- [x] New column named 'Actions' added second from the right matching wireframes
- [x] Gets report ID value for operation and conditionally displays 'Start' or 'Continue'
- [x] Text links to correct page when clicked

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [x] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements (TBC)
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Review with UX Designer
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
@patriciarussellCAS @rdromey I think this is a good candidate for next sprint, I've put it in that pipeline. Let me know if there are any concerns

**Comment by patriciarussellCAS** [comment]
@joshgamache is there a URL you can share so I can see this one? Thanks. @suhafa flagging for your design review. :)

**Comment by joshgamache** [comment]
> [@joshgamache](https://github.com/joshgamache) is there a URL you can share so I can see this one? Thanks. [@suhafa](https://github.com/suhafa) flagging for your design review. :)

https://[cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/reporting/operations](https://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/reporting/operations)

The actions column shows up here, but there are no operations right now. Going to figure out why they're not showing up in dev, but they're in local and I can show that off if need be.

**Comment by patriciarussellCAS** [comment]
Have created a follow-up ticket for confirming where users navigate to when they click "continue" #296
