### ISSUE TITLE
Discover and design reports workflow for EIO

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-reporting#278]
#### Describe the task

This ticket covers the work required to uncover how different EIOs are from the rest of the flow, what are some discrepancies to resolve and any other finer details

#### Acceptance Criteria

- [x] Document information about EIOs from BA
- [x] Create designs or a separate flow
- [x] See what impacts registration or is affected by registration
- [x] Review and refine with BA

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by suhafa** [comment]
Updates completed, only tweaking off sign-off language needed that applies to all sign-off pages by the BA.
[Wireframe can be found here](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=18885-5088&t=oB3Uq9Ir2mu0utaD-1), notes are [here](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=14176-4053&t=oB3Uq9Ir2mu0utaD-1)

**Comment by patriciarussellCAS** [comment]
Looks good.
