### ISSUE TITLE
Refine New Entrant flow with BA

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-reporting#280]
#### Describe the task

Split out ticket from #259. Has to do with cretaing new entrant wireframes

#### Acceptance Criteria

- [x] Review and implement feedback on Figma for New Entrant Screen
- [x] Review and implement feedback on Figma for Regulated part-way through the year
- [x] Compile questions to share with business area
- [x] review with business area
- [x] refine wireframes accordingly

#### Additional context

- Add any other context about the task here.
- Or here
lit out ticket from #259

**Comment by suhafa** [comment]
[New entrant](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=11404-1746&t=FN5Q3YhcGYKp3mHv-1) + [regulated partial year operations](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=14002-2013&t=FN5Q3YhcGYKp3mHv-1) wireframes created in Figma. Ticket can be closed!

**Comment by patriciarussellCAS** [comment]
I will close this ticket but with the understanding that small changes made still get made to these pages
