### ISSUE TITLE
Restructure reporting app to remove (authenticated) directory pattern

### ISSUE THREAD

**Issue by BallardRobinett** [bcgov/cas-reporting#282]
Changes to the middleware routing have broken for the current directory structure in reporting, which puts our pages which require authentication inside of a ```(authenticated)``` directory. To solve this we will change the structure to match registration.

### Dev objectives

- [x] Refactor the structure of the ```reporting``` app to remove the ```(authenticated)``` directory and replace it with the pattern in the ```registration``` app, with ```bceidbusiness``` and ```idir``` directories containing sub-directories for each role (industry_user, cas_admin, etc).
- [x] Ensure that all current pages are reachable after signing in

Prerequisite for #196

**Comment by patriciarussellCAS** [comment]
@dleard or @pbastia - would either of you be better at signing off and closing this? I don't think I can review this one. 
Thanks!

**Comment by pbastia** [comment]
I can confirm the work was done :) 
Folders were moved to the right place, no visual impact that can be checked
