### ISSUE TITLE
As a developer, I want data structures to store my report data, so that I can save reports to the database

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-reporting#283]
#### Description:

Create datastructures to store report data as described in the miro board: Whiteboarding_2024_04_12
@dleard we might need clarification about LFO data (if applicable)

#### Acceptance Criteria:

Given I am a developer
When I develop a reporting form
Then I have tables to store the data following the program configuration

Given I am a developer
When I store data from a reporting form
Then the data is stored in json format, regardless of the schema that generated it

Given I am developer
When I store data from a reporting form
Then I have the following tables to fan out the data:
- `activity_form_data` (json_data, report_version_id, activity_id)
- `source_type_data` (json_data, report_version_id, source_type_id, activity__form_data_id) 
- `unit_data` (json_data, report_version_id, source_type_data_id)
- `fuel_data` (json_data, report_version_id, fuel_id, source_type_data_id, emission_data_id)
- `emission_data` (json_data, report_version_id, gas_type_id, source_type_data_id, fuel_data_id)
- `methodology_data` (json_data, report_version_id, methodology_id)

A graph of the architecture:
<img width="1149" alt="image" src="https://github.com/user-attachments/assets/48781197-c3b5-4c55-b875-9da839e12572">

#### Development Checklist:

- [x] aforementioned tables
- [x] model tests
- [x] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by patriciarussellCAS** [comment]
I will close this ticket, however but noting that we still need some clarity on fuels (and how emissions categories fits in with them).
