### ISSUE TITLE
Task: Create a multi-select dropdown widget for our rjsf theme

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-reporting#284]
#### Describe the task
A few pages on the reporting app require users to select multiple items from a dropdown
We can display it with a component like this: https://mui.com/material-ui/react-select/#checkmarks

This card is about creating 
- a widget
- the associated documentation on how to present this through RJSF

Related: #196 

#### Acceptance Criteria

- [ ] first
- [ ] second
- [ ] third

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by pbastia** [comment]
@BallardRobinett 👀

**Comment by rdromey** [comment]
@BallardRobinett to refine

**Comment by patriciarussellCAS** [comment]
check other code bases to see if we've done this before.

**Comment by rdromey** [comment]
Widget already exists - will just need to add drop down items in separate ticket.
