### ISSUE TITLE
Discover and design flow for Simple Reports

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-reporting#285]
#### Describe the task

This ticket covers the work required to uncover how different Simple Reports are from the rest of the flow, what are some discrepancies to resolve and any other finer details

#### Acceptance Criteria

- [x] Document information about Simple Reports from BA
- [x] See what impacts registration or is affected by registration
- [x] Create designs or a separate flow
- [x] Review and refine with BA

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by suhafa** [comment]
Reviewed design with BA. Notes from Giraffe collab session (Aug 7):
- Jairo to confirm the [Emissions Data wireframe](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=16125-9003&t=89VVXDZhfdpLULmL-1) and if it needs to change as he flagged it is a bit ambiguous as to what the total emissions is attributable to
- Archita to confirm how likely it is for users to need verification for Simple reports, and this will determine whether we will keep the verification page in but as optional or let them just upload a verification statement under attachment
- Tiegan to confirm the language for the [sign-off page](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=16125-8623&t=89VVXDZhfdpLULmL-1) for simple reports
- Suha to determine how to let the user indicate what kind of report they are submitting (leaning towards having it as a drop-down in Operation Information, defaulted to 'Annual Emissions Report'

**Comment by suhafa** [comment]
Blocked until we get confirmation from BA

**Comment by suhafa** [comment]
Flow for Simple Reports is here, a few things that are minor, yet require business area to decide on are:
- Sign-off language for all reports
- CAS Registry Number, whether to include this or not (BA to discuss this internally)
Since these are minor tweaks pending business area consensus, I am confident about closing this ticket for now.

[The wireframe can be found here](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=18885-5089&t=oB3Uq9Ir2mu0utaD-1), notes can be found [here](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=14257-1952&t=oB3Uq9Ir2mu0utaD-1)

**Comment by patriciarussellCAS** [comment]
@suhafa should we try and clarify these two items in collab today? I'll wait to close this until after that meeting - just in case there are changes needed.
