### ISSUE TITLE
Backend request authorization for reporting endpoints

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-reporting#286]
#### Description:

The backend endpoints haven't been wired to the authorization framework and user roles yet
Doing this early with few endpoint existing lets us avoid a lot of refactoring at a later point, and will help iron out potential changes roles we need for the reporting app

#### Acceptance Criteria:

Given a user is authorized to use a given endpoint
When they hit that endpoint
Then the action is performed

Given a user is not authorized to use a given endpoint
When they hit that endpoint
Then the action is not performed

Here are our existing endpoints in reporting & the authorization by role that should be applied:

**GET /initial-activity-data**: authorized bceid users
**GET /build-form-schema**: authorized bceid users, idir users
**GET /operations**: authorized bceid users, idir users
**POST /reports**: authorized bceid users
**GET /report-version/{version_id}/report-operation**: authorized bceid users, idir users
**POST /report-version/{version_id}/report-operation**: authorized bceid users
**GET /reporting-year**: All users - no auth required

Applying auth was recently made easier & more reliable in https://github.com/bcgov/cas-registration/pull/2052.
Suggest giving that PR a read-through to see how it has been applied
#### Development Checklist:

- [ ] Update existing endpoints with the above permissions
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by rdromey** [comment]
@dleard @pbastia to refine further

**Comment by joshgamache** [comment]
https://github.com/bcgov/cas-registration/pull/2205

**Comment by patriciarussellCAS** [comment]
@pbastia or @dleard can I leave this one for you guys to approve and close?
