### ISSUE TITLE
Activity page - Hydrogen production

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-reporting#289]
#### Description:

[Wireframe](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=7837-20066&t=WU1VPKoUDpbR5KCv-4): 

Following #253 we have a full stack example of how to generate an activity emissions form using the API form builder service.The implementation here should be very similar to the GSC activitiy page.

Documentation on the full stack steps necessary to create an activity page are in our [docs](https://github.com/bcgov/cas-registration/tree/develop/docs/frontend)

Use the excel file (BCIERS Reporting Fields V2 in the SME channel files  - Reporting App directory) provided by IRC to determine what the necessary activity, source type, gas type, methodology, reporting fields & related configurations that need to be added are.

_Edit (2024-09-09)_
This is the first activity that has a more complicated set of logic in the methodology fields. To handle this, we're going to need to apply custom schemas instead of reporting fields in some cases.
How:
- Create a `custom_methodology_schema` model (columns: {id, json_schema})
- Add a foreign key relationship on the `configuration_element` model to the `custom_methodology_schema` model
- Create a custom schema for the Feedstock methodology that handles the array of items needed for that methodology
- Update the `handle_methodology` function in the `build_form_schema` service to check if an element has a custom schema
  - If it does, apply that custom schema directly into the methodology oneOf object
  - If not, apply reporting_fields as normal

We'll use this same pattern for other activities that have more complicated methodology field functionality going forward (Lime Manufacturing, Coal Storage)

#### Acceptance Criteria:

Given I am on the hydrogen production activity form page
When I first land on the page
Then the activity schema is fetched & displayed

Given the schema has rendered correctly
When I make selections that have dependencies (gas type, methodology)
Then the correct options and fields as defined from the configuration are shown

#### Development Checklist:

- [x] Any activities, source types, gas types, methodologies or reporting fields needed for the configuration that are not already in the database are added
- [x] The configuration relationships have correctly been added to the database
- [x] The many to many reporting field data (if needed) has correctly been added to the database
- [x] The base schema for the activity & source types have been added to the database
- [x] A routing directory/page has been added to both the industry_user & industry_user_admin flows for the activity
- [x] A parent component (named for the activity) has been added to the components in the activity directory
- [x] The page fetches the correct initial activity schema from the API service on initial load
- [x] A uiSchema exists in the components/activities/uiSchema directory for the activity & source types (will move to the database eventually, but can live here for now)
- [x] Conditional fields render dynamically as data is entered
- [x] On selecting a source type (or if there is only one, on loading the page) The first set of data fields is displayed (defaultEmptySourceTypeState)
- [x] A new `custom_methodology_schema` model has been created with the columns as described above
- [x] The `configuration_element` table has a fkey to the new table
- [x] The `build_form_schema` service has been updated to handle custom methodology schemas
- [ ] Matches the wireframe

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by ayeshmcg** [comment]
The Url for testing is:
https://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/reporting/reports/5/facilities/1/activities/hydrogen_production

**Comment by patriciarussellCAS** [comment]
Thanks @ayeshmcg 
Review notes: 
1. Methodology should be listed before Emissions and Equivalent Emissions, so it aligns with the spreadsheet. 
2. Feedstock is one word
3. When Feedstock Material Balance is the methodology selected we are missing the "Annual Hydrogen Production" fields
4. Under Feedstock Material Balance - the field "Unit for Annual Feedstock amount" should be a dropdown with the options from the spreadsheet. 
5. A design question (@suhafa) - in other forms when the select a methodology, the fields just pop up underneath. In this case, they don't and the user has to press the "+ add feedstock" button. I just want to make sure that's the correct flow. 

![Image](https://github.com/user-attachments/assets/8b877c89-1f75-44ce-b8f7-eee967bbd62e)

**Comment by dleard** [comment]
Methodology is a dependency of the selected gas type which is why they are listed afterwards

**Comment by ayeshmcg** [comment]
@patriciarussellCAS All the issues have been addressed.
