### ISSUE TITLE
Update "Review Operation Information" Page

### ISSUE THREAD

**Issue by patriciarussellCAS** [bcgov/cas-reporting#293]
#### Description:

Follow-up to #324 
Need to confirm where data is being pulled from. Need API work. 

As part of the "Review Operation Information" page (#196) users will need to have the option to select "simple report".
Selecting this option means the Industry Reporter will have a different (more simple) reporting workflow. 
The workflow for simple reporting is capture here #285 

[WIREFRAME](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=16125-9655&t=b9plrMxZQD0iQhDG-4)

This includes:
-   Report Type: Make Annual Report the default.
-   Report Type: If they select Simple Report a description box is added to explain what this means.
-   Need to ADD Registration Purpose field (so we know which type of report they are shown)
-   Update these fields so they are non-editable: Operation type, BCGHG ID, BORO ID, Registration purpose

[Simple Workflow Wireframe](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=16125-9655&t=1ZNIH6bcaqHB63jD-4)

#### Acceptance Criteria:

Given that I am an Industrial Reporter and I'm on the Review Operation Information page
The **default** selection for "report type" should be Annual Report. 

Given I am an Industrial Reporter on the Review Operation Information page and I need to fill out a simple report,
When I select the "simple report" checkbox (tbd) for my report type, 
Then the system will only show me the forms required for a simple report workflow. 

Given I have selected "simple report" for my report type
Then a description of what this means will be displayed. 

Given I view the operation information form
Then the following fields are read-only:
- Operation type
- BCGHG ID
- BORO ID
- Registration purpose

#### Development Checklist:

- [x] ReportVersion model needs an extra field: "report_type" with "Simple" or "Annual" as options. Note: We can't put this on the Report model, because this would prevent a user from changing the report type in a subsequent version, should they have gotten it wrong.
- [x] Switching between "Simple" and "Annual" hides or shows the activities and producs fields
- [x] Switching also toggles the "Simple" extra text
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by suhafa** [comment]
Confirm with BA what term to use for Partial Year. As per our last discussion, they agreed on 'Regulated Operation - Partial Year'

**Comment by patriciarussellCAS** [comment]
To discuss with team and BA

**Comment by rdromey** [comment]
@ayeshmcg to write dev checklist

**Comment by pbastia** [comment]
@patriciarussellCAS  What's the rules for a simple report? Is it something we can derive from the registration information?

**Comment by pbastia** [comment]
@patriciarussellCAS added an 'attn business area' tag for:
- the text explaining what a simple report is
- confiriming the fields on the simple report?

**Comment by zoeyli-46** [comment]
@patriciarussellCAS whats the tbd for in "When I select the "simple report" checkbox (tbd) for my report type," ?

**Comment by patriciarussellCAS** [comment]
@zoeyli-46  & @pbastia  Tiegan is working on final language to display when they select a simple report. For now, you could put the following, and we'll update it later when needed. That way we aren't blocked from making these updates to Operation Info page. 

**" Regulated or Reporting Operations should file a Simple Report if their emissions have dropped below 10,000 tCO2e. They will continue to report using the Simple Report form until they stop Schedule A activities or stay under 10ktCO2e for three years. This does not apply to Opt-ins."** 

As for confirming the data fields: We have wireframes for simple reports, but the data fields still need final signoff. We will prioritize this after the regulated operation workflow is done.

**Comment by ayeshmcg** [comment]
Update simple report description as mentioned in 
https://github.com/bcgov/cas-reporting/issues/394

**Comment by ayeshmcg** [comment]
To test, 
Go to 
https://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/reporting/reports/1/review-operator-data
when, you will be able to see label for report type, options for report type, helper text for simple report, registration puspose field. When simple report is selected - activities and products are removed.

**Comment by vesselak** [comment]
Tested in dev
