### ISSUE TITLE
Discovery: Emissions Categories & their relationship to other data

### ISSUE THREAD

**Issue by patriciarussellCAS** [bcgov/cas-reporting#294]
#### How do we create emissions categories? 

Business area is going to create an artifact for us translating what is in GGERR into an approved set of rules for how to apply emission catgories.

#### Acceptance Criteria

- [x] We have the artifact from BA

#### Additional context

Add any other context about the task here.

#### Definition of Ready:

Note: If any of the points are not applicable: delete or mark N/A

- [ ] Topic is clearly Defined.
- [ ] Task Description is Clear.
- [ ] People to speak to are identified (if applicable).
- [ ] Acceptance Criteria is Clear.
- [ ] Ticket Title is Clear.
- [ ] Ticket is reasonably Split up/sized.
- [ ] Value/Pain is Clear.
- [ ] Relevant Team Members are assigned.
- [ ] Ticket Estimated.

#### Definition of Done.

Note: If any of the points are not applicable: delete or mark N/A

- [ ] Rough User Stories Proposed.
- [ ] Follow-up Tickets created (if necessary).
- [ ] Findings are documented (if necessary).
- [ ] Reference docs/spreadsheets identified and indexed.
- [ ] Value Proposition Canvas (if required)

**Comment by dleard** [comment]
@patriciarussellCAS @suhafa  @pbastia Emission categories can be derived from data we collect (depends on source types and/or fuel) and the rules will be given to us by IRC to codify.

**Comment by patriciarussellCAS** [comment]
Business Area will provide a more clear directive for emissions categories.

**Comment by suhafa** [comment]
Received the artifact. 
- It is pending update and doesn't reflect current state
- It is missing a column for fuels
- The emissions categories themselves are not the terminologies we are referring them to as in the wireframe. The wireframe has the most updated version of the names of these categories
@patriciarussellCAS this ticket can be closed, we have a a design follow up ticket #316 for changing up the emissions summary page
