### ISSUE TITLE
Continue a Report from "Action" column in Reporting Dashboard

### ISSUE THREAD

**Issue by patriciarussellCAS** [bcgov/cas-reporting#296]
#### Description:

This a follow-up ticket to #274 
We'll need to figure out where users are taken to in their annual report when they click continue. 
Given that the report has many pages and could have different sections partially filled out, where should the "continue" button send them? 

#### Acceptance Criteria:

Given that I am an Industry Reporter
When I view the operation list on the Reporting Dashboard page
I see "Continue" in the Action column for any reports that have already been started but not yet submitted

Given that I am an Industry Reporter (SFO & LFO)
When I view the operation list on the Reporting Dashboard page
And I click on 'Continue' from the Actions column
I am taken to the Operation Information Page

#### Development Checklist:

- [x] Clicking `Dashboard> Reporting > Reports > Actions "Continue"` routes to `Review operation information` displaying submitted data and allows for form editing.
![Image](https://github.com/user-attachments/assets/62b6f991-bbf5-46a7-b7ca-f4e03d5f167e)
![Image](https://github.com/user-attachments/assets/db6a70fd-5696-45f8-a879-3dc88478f1c0)

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by rdromey** [comment]
@BallardRobinett to write up dev checklist

**Comment by patriciarussellCAS** [comment]
I wrote some AC for this ticket but still needs a Dev checklist

**Comment by rdromey** [comment]
@shon-button to write dev checklist

**Comment by shon-button** [comment]
Current [Reg implementations](https://github.com/bcgov/cas-registration/pull/2486):

Limited to: "pre-fills the first page of the form...doesn't include a put route, so if you "continue" you're actually creating a new registration"

**Comment by rdromey** [comment]
Work has been completed already.
