### ISSUE TITLE
How will our system deal with "Administrative" data? 

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-reporting#30]
There is administrative data that will be required at the registration phase as well as the emission reporting phase. 

**Acceptance Criteria:**
- [ ] Categorize which fields are considered administrative data
- [ ] Confirm which fields are required for registration and/or reporting, and how they overlap
- [ ] Identify how corrections and updates to administrative data will be reflected in both registration and reporting
- [ ] Identify what is in the MVP for both Registration and Reporting

**Goal:**

**Comment by patriciarussellCAS** [comment]
Update from Biz Area on Oct 17th: All administrative data will likely live in the Registration module. It may not all be part of the Registration MVP so would have to be considered in a future release. To be confirmed if this changes.
