### ISSUE TITLE
Update the General Stationary Combustion activity with changes from IRC

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-reporting#300]
The General Stationary Combustion activity page work was started before final approval by IRC, so there are some updates that need to  be made to be in line with the regs & the BCIERS reporting fields V2 excel sheet.

- [x] change the activity name to General stationary combustion excluding line tracing in the database
- [x] update the name in the activity schema
- [x] decide if there are places where we've abbreviated it in a way that needs to be more specific to differentiate it from the other GSC activities
- [ ] update the name wherever it is used elsewhere (ie: the route page)

**Comment by patriciarussellCAS** [comment]
I see this ticket is approved but none of the checkboxes are selected. Did these changed get made? Is this fine to close?
