### ISSUE TITLE
Activity page - General stationary combustion solely for the purpose of line tracing

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-reporting#301]
#### Description:

[Wireframe](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=7837-20066&t=WU1VPKoUDpbR5KCv-4): 

Following #253 we have a full stack example of how to generate an activity emissions form using the API form builder service.The implementation here will be really similar to GSC - without line tracing. Most of the needed database records will already exist.

Documentation on the full stack steps necessary to create an activity page are in our [docs](https://github.com/bcgov/cas-registration/tree/develop/docs/frontend)

Use the excel file (BCIERS Reporting Fields V2 in the SME channel files  - Reporting App directory) provided by IRC to determine what the necessary activity, source type, gas type, methodology, reporting fields & related configurations that need to be added are.

#### Acceptance Criteria:

Given I am on the mobile combustion activity form page
When I first land on the page
Then the activity schema is fetched & displayed

Given the schema has rendered correctly
When I make selections that have dependencies (gas type, methodology)
Then the correct options and fields as defined from the configuration are shown

#### Development Checklist:

- [ ] Any activities, source types, gas types, methodologies or reporting fields needed for the configuration that are not already in the database are added
- [ ] The configuration relationships have correctly been added to the database
- [ ] The many to many reporting field data (if needed) has correctly been added to the database
- [ ] The base schema for the activity & source types have been added to the database
- [ ] A routing directory/page has been added to both the industry_user & industry_user_admin flows for the activity
- [ ] A parent component (named for the activity) has been added to the components in the activity directory
- [ ] The page fetches the correct initial activity schema from the API service on initial load
- [ ] A uiSchema exists in the components/activities/uiSchema directory for the activity & source types (will move to the database eventually, but can live here for now)
- [ ] Conditional fields render dynamically as data is entered
- [ ] On selecting a source type (or if there is only one, on loading the page) The first set of data fields is displayed (defaultEmptySourceTypeState)
- [ ] Matches the wireframe

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by dleard** [comment]
@patriciarussellCAS URL in dev:
/reporting/activities/gsc_solely_for_line_tracing

**Comment by patriciarussellCAS** [comment]
Thanks @dleard - this worked however we need to update the title as it current says "General stationary combustion excluding line tracing" 

Also - to be consistent we need to have the entire title capitalized, so it should read: General Stationary Combustion Solely For Line Tracing

@suhafa - for your review as well.

**Comment by patriciarussellCAS** [comment]
Hey @dleard I assume the link to this activity page changed. Do you have the updated link?

**Comment by dleard** [comment]
yes! It has changed since I refactored the frontend directory (and routing) structure.
The path should be
/reporting/reports/1/facilities/1/activities/gsc_solely_for_line_tracing

**Comment by patriciarussellCAS** [comment]
Thanks! The title is still incorrect!

**Comment by dleard** [comment]
Ballard made a ticket for this #315 . It sounds like the kind of quick bugfix ticket that's perfect for a Friday afternoon! I'll do it right now
