### ISSUE TITLE
Activity page - Pulp and Paper Production

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-reporting#307]
#### Description:

[Wireframe](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=7837-20066&t=WU1VPKoUDpbR5KCv-4): 

This activity has activity data that will need to be added to the activity schema.

Documentation on the full stack steps necessary to create an activity page are in our [docs](https://github.com/bcgov/cas-registration/tree/develop/docs/frontend)

Use the excel file (BCIERS Reporting Fields V2 in the SME channel files  - Reporting App directory) provided by IRC to determine what the necessary activity, source type, gas type, methodology, reporting fields & related configurations that need to be added are.

#### Acceptance Criteria:

Given I am on the pulp and paper production activity form page
When I first land on the page
Then the activity schema is fetched & displayed

Given the schema has rendered correctly
When I make selections that have dependencies (gas type, methodology)
Then the correct options and fields as defined from the configuration are shown

#### Development Checklist:

- [x] Any activities, source types, gas types, methodologies or reporting fields needed for the configuration that are not already in the database are added
- [x] The configuration relationships have correctly been added to the database
- [x] The many to many reporting field data (if needed) has correctly been added to the database
- [x] The base schema for the activity & source types have been added to the database
- [x] A routing directory/page has been added to both the industry_user & industry_user_admin flows for the activity
- [x] A parent component (named for the activity) has been added to the components in the activity directory
- [x] The page fetches the correct initial activity schema from the API service on initial load
- [x] A uiSchema exists in the components/activities/uiSchema directory for the activity & source types (will move to the database eventually, but can live here for now)
- [x] Conditional fields render dynamically as data is entered
- [ ] On selecting a source type (or if there is only one, on loading the page) The first set of data fields is displayed (defaultEmptySourceTypeState)
- [x] Matches the wireframe

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by suhafa** [comment]
Thanks for your work on this @joshgamache Josh!
Some design feedback:
1) The stylization of the page is different than the designs, and other activity pages. Take #303, for example, it looks like this:
![Image](https://github.com/user-attachments/assets/c0e09005-235f-4c18-a5b3-ccf83781c0f7)
In the current iteration of this page however, we are missing the header style.
2) Another minor note, the collapsible is padded out way inside the box component, and needs to be moved out to align properly
![Image](https://github.com/user-attachments/assets/e0acb3be-b60a-47de-be0c-6d8a8f3f4e85)
It also needs to[ look like this](https://feathericons.com/?query=chevron)

**Comment by patriciarussellCAS** [comment]
I'd like to send this one back to "in progress" as I believe it has some errors. 
Note: 

1. Purity of Carbonate should only allow for 4 decimal places. If this will be addressed in future work just ignore. 
2. Emissions > Gas Type: CO2 looks incorrect. 

> If I'm reading the spreadsheet correctly, emissions and equivalent emissions much be listed for each methodology, so methodology needs to be listed first. 
> When Solids-HHV is selected the spreadsheet notes 3 fields that are required, but we have 6. See screenshot. 
> similar issue with Solids-CC

![Image](https://github.com/user-attachments/assets/b876cedc-6a6b-4487-ae1b-4ddd3ce43181)

@joshgamache

**Comment by dleard** [comment]
Methodology is a dependency of the selected gas type which is why they are listed afterwards. Emissions are listed for each methodology as one methodology is selected per emission record
