### ISSUE TITLE
Activity page - Refinery fuel gas combustion

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-reporting#308]
#### Description:

[Wireframe](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=7837-20066&t=WU1VPKoUDpbR5KCv-4): 

Following #253 we have a full stack example of how to generate an activity emissions form using the API form builder service.The implementation here should be very similar to the GSC activitiy page.

Documentation on the full stack steps necessary to create an activity page are in our [docs](https://github.com/bcgov/cas-registration/tree/develop/docs/frontend)

Use the excel file (BCIERS Reporting Fields V2 in the SME channel files  - Reporting App directory) provided by IRC to determine what the necessary activity, source type, gas type, methodology, reporting fields & related configurations that need to be added are.

#### Acceptance Criteria:

Given I am on the refinery fuel gas combustion activity form page
When I first land on the page
Then the activity schema is fetched & displayed

Given the schema has rendered correctly
When I make selections that have dependencies (gas type, methodology)
Then the correct options and fields as defined from the configuration are shown

#### Development Checklist:

- [x] Any activities, source types, gas types, methodologies or reporting fields needed for the configuration that are not already in the database are added
- [x] The configuration relationships have correctly been added to the database
- [x] The many to many reporting field data (if needed) has correctly been added to the database
- [x] The base schema for the activity & source types have been added to the database
- [x] A routing directory/page has been added to both the industry_user & industry_user_admin flows for the activity
- [x] A parent component (named for the activity) has been added to the components in the activity directory
- [x] The page fetches the correct initial activity schema from the API service on initial load
- [x] A uiSchema exists in the components/activities/uiSchema directory for the activity & source types (will move to the database eventually, but can live here for now)
- [x] Conditional fields render dynamically as data is entered
- [x] On selecting a source type (or if there is only one, on loading the page) The first set of data fields is displayed (defaultEmptySourceTypeState)
- [x] Matches the wireframe

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by patriciarussellCAS** [comment]
@dleard can you share the URL. I took a stab at reporting/reports/1/facilities/1/activities/refinery_fuel_gas_combustion but that didn't work.

**Comment by dleard** [comment]
Oops, sorry I shortened it a bit. It's reporting/reports/1/facilities/1/activities/refinery_fuel_gas

**Comment by patriciarussellCAS** [comment]
Reviewed in Dev. Works as expected. Matches BCIERS data field Spreadsheet. Will move to QA (in Test) for future review.

**Comment by patriciarussellCAS** [comment]
Will close for now, but noting we will need to review all the activity pages in Test as well.
