### ISSUE TITLE
Hold 1:1 conversation with Harnav about upcoming reporting work

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-reporting#31]
Let's touch base with Harnav to align on the work going forward.

**Acceptance Criteria:**
- [x] Set up time for Harnav & Team Giraffe to meet
- [x] Walk through Reporting Discovery Roadmap
- [x] Discuss future ways of collaborating
- [x] Document any next steps, if any

**Goal of this ticket:**
Ensure Harnav has an idea of the work coming up & establish how we can work together through it

**Comment by jaimiebutton** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Giraffe-Sprint-Board-64597698d333490011486ab9/issues/bcgov/cas-reporting/31?planning-poker) with Zenhub @NicoleGovvy

**Comment by patriciarussellCAS** [comment]
I believe this is closed now.
