### ISSUE TITLE
As an industry reporter, I want to see my activities in the same order every time, so that I don't get confused

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-reporting#311]
#### Description:

IRC has requested that activities are ordered like this:
General Stationary Combustion activities
Mobile Combustion
Alphabetically after the above activities

#### Acceptance Criteria:
As an industry reporter
Given I am viewing the list of activities on the facility review page
Or I am walking through the activities I selected in that page
When I see the list of activities
Then they follow the ordering pattern described above

#### Development Checklist:

- [ ] GSC activities have lower weight than all other activities
- [ ] Mobile Combustion has a higher weight than GSC activities & lower weight than all other activities
- [ ] All other activities have the same weight
- [ ] The endpoint that fetches the set of activites sorts by weight & then alphabetically by name
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by dleard** [comment]
@patriciarussellCAS  @pbastia  may not need this ticket? Was this covered by adding weights to the database?

**Comment by dleard** [comment]
To test: Order of activities can be seen on either the operation review or facility review pages. 
Screenshot:
![Image](https://github.com/user-attachments/assets/2807cb47-6a13-4209-b7a8-1d27dc33c5a0)

**Comment by patriciarussellCAS** [comment]
This worked for me. Thanks!
