### ISSUE TITLE
Bug: GSC for line tracing activity page issue - wrong title

### ISSUE THREAD

**Issue by BallardRobinett** [bcgov/cas-reporting#315]
#### Describe the Bug:

On the GSC for line tracing page from this ticket: https://github.com/bcgov/cas-reporting/issues/301

The title is the from the GSC excluding line tracing activity page.

#### Probability:

5

#### Impact:

2

<img src="https://www.getzephyr.com/sites/default/files/riksk%20matrix.jpg" alt="Bug Matrix" width="250" height="250"/>

#### Steps to reproduce the behaviour:

1. Step #1

#### Additional information:

Browser: [e.g. chrome, safari]
Version: [e.g. 22]

#### Additional Context

-

**Comment by BallardRobinett** [comment]
![Screenshot from 2024-08-15 12-26-16](https://github.com/user-attachments/assets/b2ad7ea7-2abc-4302-b917-ec36918b1aee)

**Comment by ayeshmcg** [comment]
URL for testing 
https://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/reporting/reports/1/facilities/1/activities/gsc_solely_for_line_tracing

**Comment by patriciarussellCAS** [comment]
Fix looks good. Thanks!
