### ISSUE TITLE
Re-design of emissions summary page

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-reporting#316]
#### Describe the task

The business area has updated criteria for emissions summary. We need to update the design of the emissions summary page based on the change. See also #294 

#### Acceptance Criteria

- [x] Cross-check with business area about the updates
- [x] Update design of emissions summary
- [x] Review design with devs and BA
- [x] Update the design everywhere

#### Additional context

- Emission Summary Page tickets: #142 and #202 
-

**Comment by patriciarussellCAS** [comment]
@suhafa  I've added links to the 2 user story tickets for Emissions Summary pages. Based off the outcome of this ticket these will likely need to be refined.

**Comment by suhafa** [comment]
Notes from BA:
"For the Methodology Dropdown list, there be 2 separate options: "Replacement Methodology" and "Alternative Parameter Measurement Methodology"

Upon selecting either of these aforementioned 2 options, there be a note (through an asterisk or similar) with the following text: “By selecting Replacement Methodology/Alternative Parameter Measurement Methodology, you may be contacted by Ministry staff to verify compliance.”

Following selection of either of the 2 options, a mandatory comment box will appear with a note above the comment box “Replacement Methodology/Alternative Parameter Measurement Methodology Description”"

This ticket can be converted to a dev ticket for implementation of this
