### ISSUE TITLE
Styling: Emission section in activity pages "bumps out" from the side of the grey sub box background

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-reporting#319]
The Emissions section of the activity pages has a little bump out on the right side because they're offset a little bit. Could maybe be solved with a transparent background for that section?

![Image](https://github.com/user-attachments/assets/a8fe4f06-90a0-464d-8d55-e6ff3a84af2e)

**Comment by patriciarussellCAS** [comment]
@ayeshmcg - i think this is the same as what you are working on.

**Comment by ayeshmcg** [comment]
@patriciarussellCAS I did a PR for this one, which will fix this. so can move this to pending dev review. What do you suggest?

**Comment by ayeshmcg** [comment]
Fixed this by adding background as trasparent


![Image](https://github.com/user-attachments/assets/03568c56-6cb1-458d-b7c6-1d6dd47c6e46)

**Comment by patriciarussellCAS** [comment]
Thanks! That makes sense. We'll move this to pending dev review.

**Comment by patriciarussellCAS** [comment]
I've looked through a couple of activity pages and I'm still seeing the pop-out to the right for emissions. 
I'm going to put this back into In Progress so we can discuss at stand-up. 
tagging @suhafa

**Comment by ayeshmcg** [comment]
@patriciarussellCAS  @suhafa 
The changes were not deployed to dev.It is fixed now. You can test using 
[https://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/reporting/reports/5/facilities/1/activities/gsc_solely_for_line_tracing](https://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/reporting/reports/5/facilities/1/activities/gsc_solely_for_line_tracing)

**Comment by patriciarussellCAS** [comment]
Thanks! works now :)
