### ISSUE TITLE
Hold 1:1 conversation with key Unit Heads about upcoming reporting work

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-reporting#32]
Let's meet with R&A, C&E and Chris F ahead of our Reporting discovery work to ensure we're aligned and capture their (abundant) reporting wisdom.

**Acceptance Criteria:**
- [x] Hold session with Emilie
- [x] Hold session with Chris
- [x] Hold session with Robb
- [x] Hold session with John

Goal of this ticket:
- Make sure IRC is informed & consulted about the reporting work we'll be doing
- Help our team with blockers; including ticket 28, 29, 30

**Comment by jaimiebutton** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Giraffe-Sprint-Board-64597698d333490011486ab9/issues/bcgov/cas-reporting/32?planning-poker) with Zenhub @NicoleGovvy

**Comment by patriciarussellCAS** [comment]
Nice work!!
