### ISSUE TITLE
Updates to the Operation Review page to allow for progression through the app

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-reporting#324]
The Operation review page was created when we were missing several pieces on the backend & database. We now have the pieces in place to make this page fully functional.

Todo:

- [x] /report-version/{version_id}/report-operation gets related items (activities / products) as integer ids. This will not show up properly in the form (will only show numbers, where we want names) – Needs to fetch the names & match them to Ids when fetching & saving
- [x] operation type & operation representative are currently hardcoded in the schema & should come from the database
- [x] activities & products should be fetched from the database
- [x] activities & products form fields should use a multi-select widget
- [x] Continue button should save & go on to facility review (or Person Responsible if that page exists. #255 is in the sprint)

These items are not needed for progressing through the app, They can either be tackled in this card or we can create a new card for them & do them later: 
- [x] Person Responsible should be second in the tasklist (before facility review)
- [ ] ~Sync Latest Data from Registration button does nothing. It should overwrite the corresponding report_operation data with what is in the operation table~ This will be a chunk of work, let's create a new card for it
- [x] The "Please ensure this data was accurate...” message has a hardcoded date, this should be generated from the reporting year the report is for.
- [x] It should not render the form page if the report version is not found. Currently renders an empty form page even if there is no report version

**Comment by patriciarussellCAS** [comment]
Creating a followup ticket for additional changes to this form.
