### ISSUE TITLE
Design Backlog: Review Facility Information Page

### ISSUE THREAD

**Issue by patriciarussellCAS** [bcgov/cas-reporting#326]
Design Backlog follow-up ticket for #195 

Notes: 

- Facilty name, Facility type: Should be "title case"
- TBD: Facility Type is pulled from registration - should be view only
- Top Nav bar: this is outdated and will need to be updated
- Uneditable fields need to have the proper design implemented
- Only show activities that were selected on Review Operation Information Page
- Remove activities from task list

**Comment by zoeyli-46** [comment]
closing because this hasnt been built yet for LFOs. too many changes, will revisit.
