### ISSUE TITLE
Applying emission categories to an emission record

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-reporting#333]
We have a spreadsheet from IRC in the SME channel files (under Reporting App -> Emissions Summary). This outlines the rules for how an emission category is applied to an emission.

There are a few things to note about applying emission categories:
- There are 14 "categories" in the spreadsheet.
- 9 are "basic" categories
  - Flaring emissions
  - Fugitive emissions
  - Industrial process emissions
  - On-site transportation emissions
  - Stationary fuel combustion emissions
  - Venting emissions — useful
  - Venting emissions — non-useful
  - Emissions from waste
  - Emissions from wastewater
- The basic categories have a 1:1 relationship with an emission (an emission always fits into one and only one of these categories)
- There are 3 "disaggregated" categories
  - Carbon dioxide emissions from biomass listed in item 1 of Schedule C (To be displayed as: "CO2 emissions from excluded woody biomass" in the app)
  - Other emissions from biomass listed in Schedule C (To be displayed as "Other emissions from excluded biomass" in app)
  - Emissions from non-biomass listed in Schedule C.1 (To be displayed as "Emissions from excluded non-biomass" in app)
- The disaggregated categories will not overlap with each other, but will overlap with some of the basic categories. These categories are for emissions that were generated by burning a fuel. No fuel means the emission should not be in one of these categories.
- There are 2 "special" categories
  - Emissions from the following:
    (a) general stationary combustion solely for the purpose of line tracing;
    (b) oil and gas extraction and gas processing activities, carbon dioxide transportation and oil transportation and natural gas 
    transmission, distribution and storage, limited to non-processing and non-compression activities
  - Emissions from fat, oil and grease collection, refining and storage 
- These categories will overlap with some of the basic categories, but are for specific cases as outlined in the rules excel.

So for applying an emission category we need to:
- Apply a "basic" category to an emission using the provided rules
- Apply any "disaggregated" or "special" categories (if any apply)

_Proposed solution (for dev review):_
Setup:
- Create an `emission_category` table with the 14 category names (and maybe a type? If we add types of "basic, disaggregated & special" we could add tests/validation that no emission ends up in more than 1 basic category?)
- Create a many to many relationship between `report_emission` and `emission_category`
- Add 2 columns in the fuel table: ggerr_schedule & schedule_item (the category rules depend on these 2 things for the disaggregated categories)
Implementation:
- Add a function in the backend to apply emission categories to emission records on save based on the rules in the spreadsheet

_Things to consider:_
- What needs to be versioned?
  - Should we make a different table to apply ggerr_schedule & schedule_item to fuels & version that?
  - Are we ok versioning our backend function or should it be done via more configurations?
- We will probably need robust tests for each "rule" in the excel sheet to ensure the correct categories are being applied
- Is "basic", "disaggregated" & "special" a good way to define the types - could be a BA question (although it's really for us as devs, they won't see those types)

**Acceptance Criteria**

As an analyst
When an emission is saved to the database
I want it to have the correct category or categories applied
So that I can properly group emissions for further analysis

**Development Checklist**
- [ ] To be pulled from the proposed solution above & any changes after developer review

#### Blocked By
#332

**Comment by pbastia** [comment]
Idea: for each activity/source type, as we implement it (or retroactively), we can identify all the emission cases and verify with the BA if this is correct.
Then we just write tests :)
