### ISSUE TITLE
As an industry reporter, I want to see a page for reporting non-attributable emissions so that I can enter that information if relevant

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-reporting#336]
#### Description:

Non-attributable emissions page applies to those who can enter this info if their non-attributable emissions exceeded 100 tCO2e. However, all users need to be able to see this page and select 'No' if it doesn't apply to them. Selecting 'No' will hide all the fields, whereas selecting 'Yes' will display all the fields for them.

Note, the descriptive text at the top requires BA consensus, so please make sure to confirm what to put on their exactly before implementing

[Wireframe here](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=7826-17630&t=oB3Uq9Ir2mu0utaD-1)

#### Acceptance Criteria:

Given I am on the Non-attributable emissions page
When I select "yes" in the radio widget
Then I can fill out the necessary fields for the page: activity name, source type, emission category, and gas type 

Given I am on the Non-attributable emissions page
When I select "no" in the radio widget
Then I do not see any fields to fill out
and can continue to the next page

report_non_attributable_emissions model definition:
id pkey
activity varchar
source type varchar
emission_category fkey -> emission_category
gas_type -> intersection (one way) -> gas_type

#### Development Checklist:

- [x] A report_non_attributable_emissions table exists to capture the data
- [x] There should be an RJSF dependency on the yes/no boolean to conditionally display the fields
- [x] If yes is selected, all fields are required
- [x] Activity field is a free form varchar
- [x] Source Type is a free form varchar
- [x] List of emission categories should come from the emission_category table
- [x] Set of gas types should come from the gas_type table
- [x] Can add another set of fields with the add activity button
- [x] the save & continue button saves the data to the report_non_attributable_emissions table
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by dleard** [comment]
@zoeyli-46 @patriciarussellCAS I see that this page has a dropdown to select an emission category. Are we sure the user should be selecting this? The record can have a "basic" category that can be automatically applied in the background by activity & source_type (which is what is happening for all other emission records).

**Comment by patriciarussellCAS** [comment]
Hey @dleard this is based on the spreadsheet, where BA requested it be a dropdown: "For each source type. Dropdown. Options: Flaring Emissions, Fugitive Emissions, Industrial Process Emissions, On-site Transportation Emissions, Stationary Fuel Combustion Emissions, Venting Emissions - useful, Venting Emissions - non-useful, Emissions from Waste, Emissions from Wastewater"
Do you want to confirm with Jairo?

**Comment by dleard** [comment]
Yes we should confirm if/why this is needed. The emission category should be able to be auto-calculated based on the reported activity & source type. Having the user select this sounds unnecessary and error prone.

**Comment by patriciarussellCAS** [comment]
Feedback from collab: These activities and source types are separate from the typical activities and source types we have stored in our db, so these two fields need to be freeform. The Emissions category can be a dropdown menu as it's listed in the spreadsheet. 
@dleard  or @pbastia could you review the dev checklist and update based on what we heard in giraffe collab today? Ayesha said she can pick up this ticket but we just need clarity on this stuff. 
Thanks!

**Comment by ayeshmcg** [comment]
To test:-
https://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/reporting/reports/1/facilities/f486f2fb-62ed-438d-bb3e-0819b51e3aff/non-attributable
