### ISSUE TITLE
Get a demo of Australia's reporting system

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-reporting#34]
Let's see what Australia has built! 

**Acceptance Criteria:**
- [x] Reach out to contact from Australia
- [x] Set up demo
- [x] Hold demo
- [x] Document notes & next steps, if any

**Goal of this ticket:**
Learn from others to maximize the work not done

**Comment by jaimiebutton** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Giraffe-Sprint-Board-64597698d333490011486ab9/issues/bcgov/cas-reporting/34?planning-poker) with Zenhub @NicoleGovvy

**Comment by jaimiebutton** [comment]
Update: We have been in contact with the team from Australia but have not heard back about when to schedule a demo for. Will update this ticket when I hear more!

**Comment by suhafa** [comment]
Erica had mentioned about the possibility of getting in touch with the UX team that worked on the application, do you think we can follow up with them for that? @jaimiebutton

**Comment by jaimiebutton** [comment]
Notes have been documented here: https://bcgov.sharepoint.com/:w:/r/teams/00608-DesignersInternal/Shared%20Documents/Designers%20Internal/Reporting%20Environmental%20Scan/Australia%20Notes.docx?d=w88d9f710ccc84a979ad66f13756c83f0&csf=1&web=1&e=CSWOby

**Comment by jaimiebutton** [comment]
Hey Suha, sure! I forward you the contact from Australia for follow-up.
