### ISSUE TITLE
New Entrant Information - Additional Form

### ISSUE THREAD

**Issue by patriciarussellCAS** [bcgov/cas-reporting#351]
#### Description:

For Regulated Operations who are registered as a New Entrant, they will be required to fill out a New Entrant Information form with additional information. 
This applies to both SFOs and LFOs and would be required after they have filled out the facility-level forms and the "additional reporting data" form. 
They would see this page before moving on to the compliance summary page. 

[WIREFRAME](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=11404-1746&t=aTkuFvEdWQZQvh1X-4)

Data architecture:
We will need two tables to capture this data:

report_new_entrant:
id pkey
authorization_date timestamptz
first_shipment_date timestamptz
new_entrant_period_start timestamptz
assertion_statement_certified boolean
...numeric fields for each emission category

report_new_entrant_production
id pkey
product_id fkey -> erc.product
report_new_entrant_id fkey -> report_new_entrant
production_amount numeric

#### Acceptance Criteria:

Given that I have registered as a new entrant
When I fill out my annual report
Then I need to have an additional page to provide specific New Entrant information. 
And that page is in the "Additional Information" section after the "Additional reporting data" form
And it is accessible with the `/reports/{version_id}/new_entrant_information` URL

Given I am a new entrant
When I fill out my new entrant information
Then the fields only applicable to LFO, Refineries or Rendering operations are clearly labelled as such and made non-mandatory

#### Development Checklist:

- [x] report_new_entrant table as above
- [x] report_new_entrant_production table as above
- [x] An RJSF form to capture the data shown in the wireframe
- [ ] Pull products from registration data & generate sections for each product as shown in the wireframe
- [ ] Data is saved correctly to the two new tables
- [ ] Data is loaded correctly from the two new tables
- [ ] Data can be updated correctly on save
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by rdromey** [comment]
@dleard to write dev checklist

**Comment by patriciarussellCAS** [comment]
Note: BA is confirming whether we can change the "Assertion Statement" on this page to a checkbox, rather than an upload. TBD.

**Comment by dleard** [comment]
@patriciarussellCAS I'm unclear on this AC. Is the intent to dynamically show or not show certain emission category fields?
"Given I am a new entrant
When I fill out my new entrant information
Then the fields only applicable to LFO, Refineries or Rendering operations are clearly labelled as such and made non-mandatory"

**Comment by patriciarussellCAS** [comment]
@dleard I believe @pbastia wrote that AC. My understanding is that all fields will be shown to everyone, but the last two fields on the page are optional for everyone except those who need to report that info. I think we just need language on the page to reflect that. Pierre just let me know if you had a different understanding

**Comment by pbastia** [comment]
@patriciarussellCAS I understand the same thing! This way we don't have to build logic in the form to support that either

**Comment by patriciarussellCAS** [comment]
Confirming that we do need to keep the date of first shipment on this page, as verification bodies will use this date as part of their verification process.

**Comment by patriciarussellCAS** [comment]
Confirmed that this worked for the new entrant workflow.
