### ISSUE TITLE
Review Operation Information Page - UPDATES

### ISSUE THREAD

**Issue by patriciarussellCAS** [bcgov/cas-reporting#360]
#### Description:

We have a couple of changes and additions needed for the Operation Information Page. 
[WIREFRAME](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=7845-20996&t=PZyzUsT22BOzZbXs-4)

This includes:

1. Report Type: Make Annual Report the default. 
2. Report Type: If they select Simple Report or Partial-year report a description box is added to explain what this means. 
3. Need to ADD Registration Purpose field (so we know which type of report they are shown)
4. Update these fields so they are non-editable: Operation type, BCGHG ID, BORO ID

#### Acceptance Criteria:

Given
When
Then

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by rdromey** [comment]
To be merged with #293

**Comment by pbastia** [comment]
closing, merged with #293
