### ISSUE TITLE
Design Backlog: UI Guard to inform the user of the impact of switching report type

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-reporting#370]
If the user has already begun filling out the report, and then switches their report type, then it will erase the form fields that they have already entered. Given that a user's report is not empty, and the user switches their report type, then a modal will appear asking the user to confirm the change. 

[Wireframe](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=23393-5554&t=17Jxosh7qMRbzSPl-4)

AC
If the user has entered any field after “report type”, and then they select a different report type, then this confirmation modal will appear. If the user clicks “change report type” then the report type dropdown selection will change to the new selection. If the user clicks cancel, then the report type dropdown selection will remain the same.

**Comment by zoeyli-46** [comment]
@patriciarussellCAS The design is completed here, should I close this ticket and create a new "developers" ticket, or should we repurpose this ticket and backlog it?

**Comment by patriciarussellCAS** [comment]
Thanks @zoeyli-46. I have created a tech debt ticket for this. It still needs refinement but it's here: #401 
I will close this ticket. thanks!
