### ISSUE TITLE
Attachment Page - Document Uploads

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-reporting#371]
#### Description:

As an industrial reporter, I want to upload required documents on the Attachment Page, including verification statements, documents required for WCI methodology and potentially any other uploads that may be required. 

[WIREFRAME](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=17438-5181&t=AWAp1O0enJyqJvYH-4)

#### Acceptance Criteria:

The WCI field is shown to all operations **other than** EIOs and Simple Reports, and is optional 
The Confidentiality request field is shown to **all** operations, and is optional
The Verification statement field is shown to only regulated operations, and is required if they filled out the verification form
The "additional reportable information" field is shown to only EIOs, and is optional. [Figma for EIO attachments page](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=18472-9659&t=aDdzy3aTCmTVdT5t-4)

When I upload a verification statement
Then I can see its name and a confirmation of its upload
And clicking the file name prompts a download

#### Development Checklist:

- [ ] Create attachment page route, similar to `bciers/apps/reporting/src/app/bceidbusiness/industry_user/reports/[version_id]/sign-off/page.tsx``bciers/apps/reporting/src/app/bceidbusiness/industry_user_admin/reports/[version_id]/sign-off/page.tsx` which imports attachment page component 
- [ ] Create attachment page component similar to `bciers/apps/reporting/src/app/components/signOff/signOffPage.tsx`
- [ ] In attachment page component, configure attachment schema similar to form `bciers/apps/registration/app/components/operations/registration/OperationInformationForm.tsx` which uses schemas in `bciers/apps/administration/app/data/jsonSchema/operationInformation/operationInformation.ts` to define the use of `bciers/libs/components/src/form/widgets/SelectWidget.tsx` for file uploads.
- [ ] Create db model for attachment page information
- [ ] Possibly create In/Out schemas for attachment page interaction with API endpoint  if required, see example `bc_obps/registration/schema/v2/operation.py`
- [ ] Create API endpoint to POST/PUT attachment page information, see example `bc_obps/registration/api/v2/operations.py`
- [ ] Create db service to create or update attachment page information, see example `create_or_update_operation_v2\Document Handling` which uses `DocumentService.create_or_replace_operation_document method:` for attachment handling
- [ ] **Note** Possibly implement [attachment handling improvements](https://github.com/bcgov/cas-registration/issues/2123#issue-2483563373)
- [ ] Create component vitests
- [ ] Create model tests
- [ ] Create endpoint test
- [ ] Create service tests
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by patriciarussellCAS** [comment]
@pbastia we need this functionality for reporting-only operations who meet the criteria for verification as well. Do we want that in here or a separate ticket? It's still listed as AC in bcgov/cas-reporting#199

**Comment by rdromey** [comment]
@shon-button to write dev checklist

**Comment by patriciarussellCAS** [comment]
@BCerki or @Sepehr-Sobhani  - are there functions from the uploads in registration that we could reuse for this in reporting? perhaps we could get your insight to help with this ticket?

**Comment by BCerki** [comment]
> @BCerki or @Sepehr-Sobhani - are there functions from the uploads in registration that we could reuse for this in reporting? perhaps we could get your insight to help with this ticket?

Yes, what we've done in registration can be reused, and the dev checklist in this ticket directs people to look at registration for examples. However, the way we've done it registration could use some improvement (see https://github.com/orgs/bcgov/projects/123/views/16?filterQuery=repo%3Abcgov%2Fcas-registration+-status%3Adone+file&pane=issue&itemId=80445934&issue=bcgov%7Ccas-registration%7C2123), so you may not want to reuse everything exactly as it is currently.

**Comment by pbastia** [comment]
Thanks for the review @patriciarussellCAS ! Bringing this back to in progress to fix the few missing items

**Comment by pbastia** [comment]
@patriciarussellCAS  testing URL: `/reporting/reports/1/attachments`

**Comment by patriciarussellCAS** [comment]
Thanks @pbastia 
When I try and click Save and Continue I get this error message. I tried this a couple of times doing different combinations of uploads.

 ![Image](https://github.com/user-attachments/assets/f38c5ad4-2994-4f30-a0b0-b89e55cc4700)

**Comment by patriciarussellCAS** [comment]
Also - I have 2 language updates please: 
1. Please upload any of the documents below that **are** applicable to your report
2. To make the "note" at the bottom more clear, please change to: "Notes on Confidentiality Requests"

**Comment by pbastia** [comment]
@patriciarussellCAS I've filed a couple of tickets: https://github.com/bcgov/cas-reporting/issues/417 and https://github.com/bcgov/cas-registration/issues/4859

Looks like we display a page even if there is no report version that exists with that ID!
You'll need to start a report from the dashboard first, then visit the link with the appropriate version ID

**Comment by patriciarussellCAS** [comment]
Thanks @pbastia
