### ISSUE TITLE
Update Additional Reporting Data Page

### ISSUE THREAD

**Issue by ayeshmcg** [bcgov/cas-reporting#372]
**Description:**
Currently, the "Electricity generated" field is displayed alongside other fields. We need to move it to the bottom under the heading "Additional Data".

Additionally, the "Electricity generated" field is currently visible only when the Registration Purpose is Regulated Operation Only. We need to confirm this behavior and make any necessary adjustments accordingly.

**Comment by patriciarussellCAS** [comment]
Feedback from Jairo and Emilie:
The Electricity generated field only needs to be shown to Regulated Operations. 
This is opposite from what we original thought, but has been confirmed. Reporting-only operations do NOT see electricity generated field. 
Thanks!

**Comment by ayeshmcg** [comment]
To Test:- 
https://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/reporting/reports/1/additional-reporting-data
