### ISSUE TITLE
Button display & functionality should align with design

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-reporting#392]
Several of our buttons have drifted in design and functionality from the intended design. The purpose of this ticket is to update our buttons to be displayed and function as intended.

Design guidelines on buttons:
https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=24707-7130&t=Fy2tRxFJ8qATm7X7-4

Todo:
- [x] Operation information buttons align with design (Buttons should be Back, Save, Save & Continue)
- [x] Activity page buttons align with design (Buttons should be Back, Save, Save & Continue)
- [x] Look for other reporting pages/components where the buttons are not displayed/function as intended
- [x] Back buttons should go back one step in the task list OR if on the first item of a task list, should go to the last item of the previous page
- [x] Save button should validate and save data
- [x] Save & Continue button should validate/save data & move on to the next item in the task list OR if on the last item in a step, go to the next page
- [x] Add solution for dylan's comment (person responsible save & continue bug)

**Comment by vesselak** [comment]
@nanyangpro please review for design consistency

**Comment by patriciarussellCAS** [comment]
I'm still having some issues clicking through certain pages, but overall I have noted that buttons are consistent and almost all of them are working as expected. I am not ready to accept this ticket yet, but feel it shouldn't be a blocker for the next release.

**Comment by patriciarussellCAS** [comment]
There are a couple of outstanding glitches related to buttons, but they have been captured in follow-up bug tickets. 
I will consider this ticket done.
