### ISSUE TITLE
Update Simple Report Description on Review Operation Information page

### ISSUE THREAD

**Issue by zoeyli-46** [bcgov/cas-reporting#394]
Update the description to the following
Simple Reports are submitted by reporting operations that previously emitted greater than or equal to 10 000 tCO2e of attributable emissions in a reporting period, but now emit under 10 000 tCO2e of attributable emissions and have an obligation to continue reporting emissions for three consecutive reporting periods. This report type is not applicable for any operations that received third party verification in the immediately preceding reporting period, and is not applicable for opted-in operations.

**Comment by zoeyli-46** [comment]
@ayeshmcg

**Comment by rdromey** [comment]
Covered by #293
