### ISSUE TITLE
Activity formState is persisted when swapping activities causing an error on save

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-reporting#395]
#### Describe the Bug:
The useEffect() in the ActivityForm component is problematic & that has been highlighted by the load-data work that has been done in #345 . That work has unearthed a bug where only one activity can currently be saved, as the formState is being persisted across activity forms. Since the formState is persisted, when the data attempts to save, the API gets a 404 in that process as it tries to look for source types from multiple activities worth of data.

A potential quick stopgap solution (though we should still handle the formState being persisted & the wonky-ness of the useEffect() function):
- add the record IDs to the schema
- use RJSF's omitExtraData functionality, which will prune the extra source type data from the formData when saving

#### Steps to reproduce the behaviour:

1. Add a console.log() in the handleSave() function of ActivityForm before the API call to log data.formData
2. Init a report with at least 2 activities selected
3. Enter & save data for the first activity
4. Navigate to the second activity & attempt to enter data & save it
5. You will see an error & if you inspect the results of the console.log() you'll see that the data from the previous activity is in the payload

-

**Comment by dleard** [comment]
The bug fix can be tested by entering and saving data in more than one activity page

**Comment by patriciarussellCAS** [comment]
I was able to confirm this works while testing the alumina activity page :)
