### ISSUE TITLE
Tech-Debt:Add Delete Service for Non-Attributable Emissions Page

### ISSUE THREAD

**Issue by ayeshmcg** [bcgov/cas-reporting#396]
Description:
Implement a delete service for the Non-Attributable Emissions page with the following requirements:

If the "Non-Attributable Exceed" radio button is set to "No," remove all related data, including many-to-many linked records.
If any data in this section is deleted, ensure all associated records are also removed to maintain data consistency.

Dev Checklist:
- [x]  All associated data is removed when "No" is selected for "Non-Attributable Exceed."
- [x]  Cascading delete functionality is verified, ensuring no orphaned records remain.

**Comment by ayeshmcg** [comment]
@dleard  I created a card for handling non-attributable emissions page delete.

**Comment by patriciarussellCAS** [comment]
I'm unable to get to the non-attributable emissions page from the reporting dashboard so am unable to review this.

**Comment by ayeshmcg** [comment]
@patriciarussellCAS 
You can try using 
https://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/reporting/reports/2/facilities/f486f2fb-62ed-438d-bb3e-0819b51e3aff/non-attributable

**Comment by patriciarussellCAS** [comment]
Thanks! Works great.
