### ISSUE TITLE
Switching Report Type part-way through

### ISSUE THREAD

**Issue by patriciarussellCAS** [bcgov/cas-reporting#401]
#### Tech Debt Triage

If the user has already begun filling out the report, and then switches their report type, then it will erase the form fields that they have already entered. Given that a user's report is not empty, and the user switches their report type, then a modal will appear asking the user to confirm the change.

[Wireframe](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=23393-5554&t=17Jxosh7qMRbzSPl-4)

AC
If the user has entered any field after “report type”, and then they select a different report type, then this confirmation modal will appear. If the user clicks “change report type” then the report type dropdown selection will change to the new selection. If the user clicks cancel, then the report type dropdown selection will remain the same.

#### Risk Value Scoring:

| Level  | Value                 |
| ------ | --------------------- |
| High   | <div align="center">3 |
| Medium | <div align="center">2 |
| Low    | <div align="center">1 |

| Technical Debt - Risk Types                                                                                                   | Level | Value |
| ----------------------------------------------------------------------------------------------------------------------------- | ----- | ----- |
| Business Area Risk - Risk of business area visibility / damage to user experience                                             |    0   |   0    |
| Developer Fault Risk - How likely will this tech debt cause a future error related to coding on top of it                     |    0   |   0    |
| System Fault Risk - Risk of system errors or application downtime                                                             |    0   |   0    |
| Time Scale Risk - Compound risk effect if left alone. How much more difficult to fix or dangerous will this become over time? |    0   |   0    |
| Time Sink Risk - How much will this tech debt slow the development process down                                               |    0   |   0    |
| <div align="right">**TOTAL SCORE:**                                                                                           |    0   |   0    |

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item

**Comment by patrickisaac** [comment]
Prod Checklist Session Notes:
- This is related to #384

**Comment by rdromey** [comment]
@patriciarussellCAS to close and put in ticket #383
