### ISSUE TITLE
Document Network Policies and practices

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-reporting#409]
#### Describe the task

As part of the technical documentation for the app, the team has been asked to outline the use of KNPs and what are the allowed communication paths between the different pieces of the app.

#### Acceptance Criteria

- [ ] a .md file in the docs folder
- [ ] List of recommendations

#### Definition of Done

- [ ] first
- [ ] second
- [ ] third

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by pbastia** [comment]
👀  @vesselak @andrea-williams @dleard

**Comment by patriciarussellCAS** [comment]
Some information has already been sent to MISO. Doesn't look like this is needed.

**Comment by rdromey** [comment]
Our network policies were accepted by the OCIO, so no further documentation is required.
