### ISSUE TITLE
Tech Debt: Update Navigation for New Entrant Registration

### ISSUE THREAD

**Issue by ayeshmcg** [bcgov/cas-reporting#414]
**Description:**
Update the navigation logic for the Additional Reporting Data page with the following requirements:

- If the "Registration Purpose" is set to "New Entrant", the "Save and Continue" button should navigate to the New Entrant Information page.
- If the "Registration Purpose" is set to any value other than "New Entrant", the "Save and Continue" button should navigate to the Compliance Summary page.

Dev Checklist:
- [x] Ensure the navigation logic routes users to the New Entrant Information page when "Registration Purpose" is "New Entrant".
- [x] Verify that users are routed to the Compliance Summary page for all other registration purposes.
- [x] Add appropriate unit and integration tests to validate navigation behavior.
- [x] Ensure that when the user is on the Additional Reporting Data page, it displays any previously entered data in the corresponding fields.

**Comment by patriciarussellCAS** [comment]
this worked!
