### ISSUE TITLE
Task: Placeholder for the Final Report Review page

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-reporting#420]
#### Describe the task

We need a placeholder to be able to complete the SFO workflow without having this summary page
URL: `reports/<version_id>/final-review`

#### Acceptance Criteria

- [x] a placeholder page at `reports/<version_id>/final-review`
- [x] clicking "submit and continue" continues to the signoff page
- [x] meets the DOD

#### Definition of Done

- [x] it's done!

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by pbastia** [comment]
@patriciarussellCAS this is the pre-req for #149

**Comment by pbastia** [comment]
Testing URL: reports/1/final-review

**Comment by patriciarussellCAS** [comment]
I'm getting a "not Found" at this URL: https://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/reports/1/final-review
Did I get the link wrong?
@pbastia

**Comment by pbastia** [comment]
@patriciarussellCAS sorry! it should be https://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/reporting/reports/1/final-review

**Comment by patriciarussellCAS** [comment]
Thanks! Placeholder works.
