### ISSUE TITLE
Review Operation Info Page: Empty Activity and Products

### ISSUE THREAD

**Issue by patriciarussellCAS** [bcgov/cas-reporting#438]
#### Describe the Bug:
Using Operation 3 an the test scenario, on the Review Operation Information page, the Reporting Activities and Regulated Products fields are empty. They *should* be pre-populated from registration. They also can't be left empty if the Operation is regulated (regulated, new entrant or opt-in), which is the case here. 

#### Probability: 4

(How likely the bug is to happen, scored from 1-5. For example, probability of 5 is something like "it happens to all users every time they log in." whereas probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

#### Impact: 4

(How bad the bug is when it does happen, scored from 1-5. For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected." whereas effect of 1 is "It makes some styling look a little bit weird.")

<img src="https://www.getzephyr.com/sites/default/files/riksk%20matrix.jpg" alt="Bug Matrix" width="250" height="250"/>

#### Steps to reproduce the behaviour:

1. Step 1 Reporting Dashboard > Continue report for Operation 3
2. Step 2 On the Review Operation Info page observe that activities and products are empty 
3. Step 3 Click Save and Continue
Users should NOT be able to proceed if either of these fields are empty. 

*Additional issue: Operation 3 in Registration includes a list of activities and products. These are supposed to be pre-populated in reporting based on what was selected in Registration. 

#### Additional information:

Browser: [e.g. chrome, safari]
Version: [e.g. 22]

#### Additional Context

-

**Comment by pbastia** [comment]
This is something odd, that I can't reproduce

**Comment by pbastia** [comment]
Fix will be to validate the presence of data in the activities and products

**Comment by patriciarussellCAS** [comment]
I was using Operation 3 for this scenario. Does it look different for you?
