### ISSUE TITLE
Plan 1:1s with R&A and C&E Analysts

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/cas-reporting#44]
#### Goal of Ticket
Get an understanding of staff work, processes, pain points, what works/doesn't work in order to help build out the future state map.

#### Describe the task

Plan user research sessions with staff from the business areas so we can learn/see specifically how they do their work, use systems, understand pain points etc.

#### Acceptance Criteria

- [x] Plan session format
- [x] Identify staff from business area to connect with (incl. potentially C&E: Harnav, Adit / R&A: Andrea, Amos / ICU: Jairo)
- [x] Book meetings with staff (1 hr max)

#### Additional context

Add any other context about the task here.

**Comment by NicoleGovvy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Giraffe-Sprint-Board-64597698d333490011486ab9/issues/bcgov/cas-reporting/44?planning-poker) with Zenhub @NicoleGovvy @jaimiebutton

**Comment by NicoleGovvy** [comment]
Have emailed SMEs.

**Comment by patriciarussellCAS** [comment]
Closing!!
