### ISSUE TITLE
SFO should NOT see Review Facility Info Page

### ISSUE THREAD

**Issue by patriciarussellCAS** [bcgov/cas-reporting#440]
#### Describe the Bug:
Currently in our workflow an SFO will see Review Operation Information > Person Responsible > Review Facility Info > Activities

They should not see the Review Facility Info page, but rather go straight to Activities. As shown in the SFO [wireframes](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=7845-20996&t=QiLdABnjjZCGbcvS-4). 

Their list of activities will be based on what was selected on the Review Operation Page. 
#### Probability: 5

(How likely the bug is to happen, scored from 1-5. For example, probability of 5 is something like "it happens to all users every time they log in." whereas probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

#### Impact: 4

(How bad the bug is when it does happen, scored from 1-5. For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected." whereas effect of 1 is "It makes some styling look a little bit weird.")

<img src="https://www.getzephyr.com/sites/default/files/riksk%20matrix.jpg" alt="Bug Matrix" width="250" height="250"/>

#### Steps to reproduce the behaviour:

1. Step 1
2. Step 2
3. Step 3

#### Additional information:

Browser: [e.g. chrome, safari]
Version: [e.g. 22]

#### Additional Context

-

**Comment by ayeshmcg** [comment]
We also need to refactor the activities visible in task list on the this page 
<img width="1136" alt="Image" src="https://github.com/user-attachments/assets/3fa5a3a7-e238-46ab-834d-8f844acb10d0" />

As this list is coming from the ones user selected in registration, but even if we change activities in Review Information Page, those are not reflected here

**Comment by ayeshmcg** [comment]
@patriciarussellCAS  the list of activities visible here should be ones user selected on Review Information page right? and not the ones in regsitration?

**Comment by patriciarussellCAS** [comment]
Yes, that makes more sense. Thanks @ayeshmcg 
I feel like I added the task list issue to another ticket, but let me confirm!

**Comment by ayeshmcg** [comment]
@patriciarussellCAS  The task list has been fixed in this one.

**Comment by patriciarussellCAS** [comment]
Confirmed in the walkthrough today. Thanks!
