### ISSUE TITLE
Reporting Attachments: verification statement is mandatory under certain circumstances

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-reporting#445]
#### Description:

At the same time as #405 :
For any user who has a mandatory verification requirement and fills out the verification page, then the verification statement upload on the attachments page must be mandatory.

Goal: a user can't navigate to the submit page without uploading a file as a verification statement.

#### Acceptance Criteria:

Given I am an industrial reporter
And my reporting circumstances require that I submit a verification statement
When I am on the Attachments page
Then I can't submit the page until I have uploaded a file in the verification statement form.

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

#### Definition of Ready (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

#### Definition of Done (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by patriciarussellCAS** [comment]
Thanks for pushing this through. I can confirm that this works for Regulated Operations. 
We'll need a follow-up ticket to confirm it works for +25KT Reporting Operations and *doesn't* work for Reporting Operations or EIOs. Otherwise I consider this closed.
