### ISSUE TITLE
Final Submit: clicking the submit button should display an error if no verification statement was submitted in the report

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-reporting#449]
#### Description:

- display error
- fix tasklist links so that the user can navigate to the attachments page

#### Acceptance Criteria:

Given I am an industrial reporter 
When I submit a report
And I didn't upload a verification statement
Then the system displays an error

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

#### Definition of Ready (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

#### Definition of Done (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
@shon-button here's the card

**Comment by pbastia** [comment]
@shon-button a draft of the work is done in https://github.com/bcgov/cas-registration/pull/2600, if you can have a look tomorrow morning :)

**Comment by patriciarussellCAS** [comment]
This worked!
