### ISSUE TITLE
Report Summary: What information is displayed in the Report Summary

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-reporting#45]
Background: 
At the end of the reporting process Regulated Operations will be shown a Report Summary. We need to scope out and confirm a) what information is displayed and b) how this information is calculated. 

**Acceptance Criteria:**
- [x] Add the Report Summary to the future state blueprint
- [x] Work with ES & SMEs to confirm what information will be included in the Report Summary (Harnav has created a draft)
- [ ] Confirm how this will work for LFOs specifically??

DOD: 
- [ ] Confirm IRC decision on report summary information & get sign-off

GOAL: 
To have a final decision on what is displayed in the Report Summary

**Comment by patriciarussellCAS** [comment]
Decision from Chris Fleming: Yes to the following questions

1. Will Industry see their total emissions as it relates to their emissions limit in the Reporting app (meaning the number that will be used for their compliance obligation)? 
2. Can Industry assume this number (even if it is framed as an “estimate”) is the one used to calculate their compliance obligation? 
" Obviously we still need to work out the actual compliance obligation process… but for system design this makes sense." 

Is this enough to close this ticket? Or should we dig in deeper?

**Comment by jaimiebutton** [comment]
Thanks @patriciarussellCAS . We'll still need to find out if they're shown their financial obligation right away which is tied into the NOA work happening this week.

**Comment by patriciarussellCAS** [comment]
Review ticket and include a definition of done.

**Comment by patriciarussellCAS** [comment]
Current Status - March 21 2024: 
- IRC has not confirmed what information will be presented in the Report Summary. 
- Specifically, they need to confirm whether information will be presented at the Facility or Operation Level

In the meantime, another ticket will be created to focus on the calculations needed for this Summary.

**Comment by rdromey** [comment]
Work on this will be continued in ticket #117

**Comment by patriciarussellCAS** [comment]
The scope of this has changed so I will close this ticket. Relevant work is captured in ticket #146
