### ISSUE TITLE
Roughly Map Out High-Level Divisors

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-reporting#50]
Let's map out the sector-based divisors for reporting. What we're looking to do is identify which, if any, portions of reporting apply to _all_ operations, and which portions will be dependant, not just on sector but _any_ factor involved that creates a fork in process, e.g. "if X then you must do Y, otherwise you do Z". As this is uncovered, any and all interrelatedness of the data should be recorded. A good example of this would be calculations. If we hear "X is used with Y to calculate A" we should map out that relationship, and start recording where to find official formulae. Categories to consider collecting include:
- Dependencies
- Formulae
- Conditions
- Unique behaviours / conditions / circumstances
- ...And who to talk to / where to look for each of them.

**Acceptance Criteria:**
- [ ] Identify who should be part of this work
- [ ] Create a map of high-level divisors & the interrelatedness of the data
- [ ] Include WCI Methodology
- [ ] Identify sections that have unique policy surrounding them, and who the primary contact is for each
- [ ] Break other front-end related cards out as specific categories that we should be tracking / mapping surface
- [ ] Break other back-end/calculation related cards out as specific categories that we should be tracking / mapping surface

**Comment by rdromey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Giraffe-Sprint-Board-64597698d333490011486ab9/issues/bcgov/cas-reporting/50?planning-poker) with Zenhub @mikevespi @jaimiebutton @NicoleGovvy

**Comment by patriciarussellCAS** [comment]
Adding a note that we should include the full list of WCI methodology as part of this mapping work, as it's a factor for which data is provided for each sector. 
These can be found here: https://www2.gov.bc.ca/gov/content/environment/climate-change/industry/reporting/quantify

**Comment by mikevespi** [comment]
The main artifacts from this work can be found in the `Reporting: Divisors & Data Fields` miro board. Many of the questions have been addressed in the shared OneDoc with the SMEs.
