### ISSUE TITLE
Internal user research analysis

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/cas-reporting#53]
#### Goal of Ticket
We've got a lot of great insights and information from CAS staff - now what did we learn?

#### Describe the task

Analysis of internal user research.

#### Acceptance Criteria
- [x] Transcribe notes
- [x] Map out process for current state and roll up into the current blueprint
- [x] Add emotive layer
- [x] Opportunity log for magic wand items
- [x] Completed by Dec 21, 2023

**Comment by rdromey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Giraffe-Sprint-Board-64597698d333490011486ab9/issues/bcgov/cas-reporting/53?planning-poker) with Zenhub @NicoleGovvy @jaimiebutton
