### ISSUE TITLE
Present research findings (internal & external research)

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/cas-reporting#55]
Let's provide a summary of research findings (internal & external) for the DST PO/product vision group in January.

#### Acceptance Criteria
- [ ] Identify what format will be best (document, Miro, presentation etc.)
- [ ] Prepare documentation to report out
- [ ] Provide report out on the findings/recommendations for internal and external research.
- [ ] If applicable, record segment for future reference

#### Additional context
We may want to include usability testing from Moose but would need to confirm.

#### Goal of Ticket
- Ensure the business area is aware of the research done
- Pass along any helpful tidbits
- Get some buy-in to support future research

**Comment by rdromey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Giraffe-Sprint-Board-64597698d333490011486ab9/issues/bcgov/cas-reporting/55?planning-poker) with Zenhub @jaimiebutton @NicoleGovvy

**Comment by patriciarussellCAS** [comment]
External research results were presented at Spring 7 Review. Internal findings will be provided as part of user story mapping.
