### ISSUE TITLE
Create Transition Documentation

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-reporting#56]
Let's document Jaimie's brain!

Acceptance Criteria:
- [x] Do an initial brainstorm of documentation
- [x] Speak with POs about what kinds of documentation would be helpful
- [x] Create tickets to capture documentation next steps

Goal of this ticket:
- Make sure some things can be transferred from Jaimie's head to the team

**Comment by rdromey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Giraffe-Sprint-Board-64597698d333490011486ab9/issues/bcgov/cas-reporting/56?planning-poker) with Zenhub @jaimiebutton @suhafa @patriciarussellCAS @NicoleGovvy

**Comment by jaimiebutton** [comment]
A whackload of tickets have been created to split this out, closing this ticket now :)
