### ISSUE TITLE
Identify from a UX lens, what fields we need from registration that affect reporting

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-reporting#59]
#### Describe the task
Going off #28, we want to identify which fields from registration affect reporting and on a system design perspective, how will reporting live in the app?

For this we will need to plan collaboration with team Moose to understand their scope for registration part 2 and have a few touch points in place for future collaboration

#### Acceptance Criteria

- [x] Add POs to OBPS Design syncs
- [ ] Book design collaboration session with Nan for outstanding design decisions to be made
- [ ] what does the landing page look like after the user comes back for reporting 
- [x] Have a wireframe party to confirm our assumption
- [x] Document design decision from wireframe party

#### Additional context

* Add any other context about the task here.
* Or here

**Comment by patriciarussellCAS** [comment]
@suhafa - I have booked a "wireframe part 2" party (Jan 9) with Developers to help discuss this ticket.

**Comment by suhafa** [comment]
@nanyangpro Hi Nan! We hope to have a system in place for Moose and Giraffe to sync up and be aware of changes and important updates. Tagging you on here if you have any more ideas for team collaboration + design collaboration work we hope to do together!

**Comment by rdromey** [comment]
Combined with #166
