### ISSUE TITLE
Discovery for the Verification Process in Reporting

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-reporting#6]
We will need to scope out how verification fits into the workflow of our new system, and what specifically needs to be provided in the system to fulfil verification requirements. 

We have a document from the business area outlining what information they'd like to include 

Link to the [verification fields document](https://bcgov.sharepoint.com/:x:/r/teams/00605/Shared%20Documents/Compliance/Reporting%20app/Verification%20questions.xlsx?d=w2dec3e0fa53f452aa145383f74517cfe&csf=1&web=1&e=RqE6Mk&nav=MTVfezgwQTMwNzFGLUFDRjEtNDI1RC1BNDZBLTAyNzNENzU2NENDQX0) shared by business area

Acceptance Criteria:
- [x] Identify from the business area who we should speak with
- [x] Book a session to walkthrough the vision for verification in MVP
- [x] Plan session
- [x] Document outcomes
- [x] Create user story ticket(s)

 Potential Questions for the Business Area: 
- [x] Will the information/data being verified for OBPS be different than what used to be verified? If so, what is different? 
- [x] What format should we receive the verification statements in? (for example, PDF?)
- [x] What information can we get Regulated Operations to fill out in the system to support verification? (Harnav has created a list linked above)

GOAL of TICKET: 
- [x] Understand the MVP needs for verification.
Deadline: Plan and book the discovery session this sprint, run the discovery session next sprint. 

A future card exists to scope out what more comprehensive verification looks like - see #99.

**Comment by jaimiebutton** [comment]
Hey @patriciarussellCAS , can we chat more about what this is?

**Comment by NicoleGovvy** [comment]
Notes from conversation with Patricia on Verification:

Verification

- What info is verified, is this going to change?
    - Will be required for everybody now with new rules.
    - Patricia unsure if opt-ins will need to verify (assuming yes)
        - Wants system to help guide them correctly to help submit
        - What form does the verification come in?
        - Will we need verifiers to have access to the reporting app?
        - At what stage does it happen? Need to happen at emissions report? If they failed verification what does that do? What happens in the system?
- WHO VERIFIES?
    - Patricia thinks it’s mostly businesses
    - They’ve been very engaged, they may be worried there’s too much demand and not enough capacity
        - John from compliance used to have a quarterly check-in from verifiers
        - Engagement was going to plan engagement for verifiers specifically
        - Will they need a portal? Right now PDF is submitted via SWRS which isn’t very helpful. Do they just need a checkbox.

**Comment by jaimiebutton** [comment]
Hey @patriciarussellCAS , do we want to have this answered before user stories?

**Comment by patriciarussellCAS** [comment]
Hey @jaimiebutton - sorry I only saw your comment now! I think we'll need the "definition of ready" questions answered before user stories, but may not have the whole thing fleshed out.

**Comment by patriciarussellCAS** [comment]
Hey @NicoleGovvy and @suhafa - I have refined this ticket to capture step one for scoping verification: running a discovery session with the BA to understand the ideal future state for verification in our system. Please review what I have written above and change as needed. Happy to discuss more if that's helpful. Thanks!

**Comment by patriciarussellCAS** [comment]
@NicoleGovvy you mentioned that it might make more sense to focus on what we can do for the MVP (i.e. the additional fields link above from Harnav). If that's the case, did you want to update this ticket to reflect the specific work to capture that and then we can come back to a full "future state" discovery session at a later date?

**Comment by NicoleGovvy** [comment]
@patriciarussellCAS I've narrowed the scope down here and linked to the post-MVP verification card we have.
