### ISSUE TITLE
Create information architecture diagram for Reporting

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-reporting#60]
#### Describe the task

Create an preliminary information architecture diagram on the basis of existing service design work

#### Acceptance Criteria

- [x] identify a format for IA most suitable for the team
- [x] comb through existing Miro boards to create a draft IA
- [x] review with Patricia
- [x] share with devs
- [x] Iterate

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by Dianadec** [comment]
Might be dependent on the user story mapping - also might need to be refined/changed. ( @suhafa )

**Comment by suhafa** [comment]
Created draft IA and shared with the team for a review. Please see the 'Reporting IA' board in the 'BCIERS IA & Workflows' Miro board for the artifact.

**Comment by patriciarussellCAS** [comment]
Thanks @suhafa , this looks good. Do you think we should show this to the BA before closing, or will there be follow-up tickets for future work?

**Comment by suhafa** [comment]
I'll be sharing workflows for allocation of emissions and can club in sharing this with the business area too!
