### ISSUE TITLE
Preparation for User Story Mapping - Reporting

### ISSUE THREAD

**Issue by patriciarussellCAS** [bcgov/cas-reporting#62]
Description:
For all the work required to be completed prior to our user story mapping session on Jan 30.

**Comment by Dianadec** [comment]
Preparation:
- Logistics: Who, what's the goal, schedule, in-person, hybrid etc
- Business supporting content: bring forward research (setting the context)
- --- > who will prep what part of the context
- ----> during the session, who is speaking to what?
- -----> how are we including that context as a bare bones map to build off of
- Facilitation
- -- designing the miro board or in-person board
- gathering stickies
- setting up parking lot, agenda, blah

Need:
- validate stuff done with the business area before this session:
- ---> eg: future state blueprint (TASK TODO: setup review to solidify/sign off on it) (INCLUDE: Unit heads, director level pseudo-decision makers.)
- --->

**Comment by Dianadec** [comment]
@rdromey Let's connect this week and next week about the plan for this and also reach out to designers :) cc @patriciarussellCAS

**Comment by Dianadec** [comment]
Suggestion to consider: Add start and end points of the map. Clarify where we are starting in terms of reporting. (eg: the user has registered in BCIERS)

**Comment by Dianadec** [comment]
https://miro.com/app/board/uXjVN4hyuug=/
