### ISSUE TITLE
Initialize Pytest

### ISSUE THREAD

**Issue by joshgamache** [bcgov/cas-reporting#73]
**Dev Story**:
_I want_ Pytest to be set up
_because_ it will be needed for backend Python and Django testing
_and this will help me to_ ensure the backend can be tested.

**Acceptance criteria**:

1. Pytest runs locally
2. Sample test passes

## Consideration and notes

- See [CI: Add backend test by Sepehr-Sobhani · Pull Request #234 · bcgov/cas-registration (github.com)](https://github.com/bcgov/cas-registration/pull/234) for Cas-reg context

## Tasks

- [ ] Pytest configured in line with cas-reg
- [ ] Write a sample test

**Comment by rdromey** [comment]
Moved to monorepo model, no longer completing
