### ISSUE TITLE
Initialize ShipIt for -dev namespace 

### ISSUE THREAD

**Issue by joshgamache** [bcgov/cas-reporting#76]
As a temporary workflow Reporting will be developed in the `giraffe-develop` branch. We don't want to deploy to the same namespace as they are while we sort out how we will work in tandem. As a result, we need to setup our CD to deploy `giraffe-develop` to the `96fff4-dev` namespace.

**Acceptance criteria**:

- [ ] ShipIt configured to automate releases of giraffe-backend and frontend to the `96fff4-dev` namespace

**Comment by pbastia** [comment]
Pulling out of this sprint with a backlog refinement tag. This card will only apply to the reporting frontend piece @patriciarussellCAS

**Comment by pbastia** [comment]
Closing, replaced by #164
