### ISSUE TITLE
Conduct research analysis on ext. user Reporting sessions

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-reporting#8]
Wow, we've learned so much from these ext. user sessions! What a ride.

Acceptance Criteria:
- [x] Compile findings from ext. user interviews about Reporting
- [x] Pull out challenges, opportunities & insights
- [x] Theme findings into key categories
- [x] Generate list of requirements/opportunities
- [x] Line opportunities into chronological order
- [x] Add requirements into future state blueprint

Goal of ticket:
- Make sense of all that we've learned to find common patterns & ways forward

**Comment by jaimiebutton** [comment]
Hey @NicoleGovvy ! Creating this ticket so we have it in our backlog for whenever we're ready. Feel free to add :)

**Comment by rdromey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Giraffe-Sprint-Board-64597698d333490011486ab9/issues/bcgov/cas-reporting/8?planning-poker) with Zenhub @NicoleGovvy @jaimiebutton
