### ISSUE TITLE
Create a lo-fi wireframes to outline solutions for reporting

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-reporting#86]
#### Describe the task
After our wireframe party we identified a few unknowns: 
- Operations + Facilities, will it be in the same card on the dashboard?
- How do we let users update Operator info fro registration?
- Operation + facility need to be filled out, then they need to fill out their emission reports?
- What happens when their operations info changes? How will it affect reporting?
- Should we have action oriented card titles? Or categories?

To address the above the team identified that creating user task flows can help us identify immediately how the user flow should be and get clarification from the business area, and test with them if the solution works and if there are any technical restraints

#### Acceptance Criteria

- [x] Sync with Nan and Zoey
- [x] List user goal for user flows to be tested and validated (i.e., submit emissions report, submit compliance obligation) 
- [x] Review word doc to gain insight into business area decisions
- [x] Create lo-fidelity wireframes
- [x] Review with POs + devs to refine them further
- [x] Share with business area and validate the user flow 
- [x] Refine it further

#### Additional context
* 
*

**Comment by suhafa** [comment]
@zoeyli-46 barebones of the ticket are here!

**Comment by zoeyli-46** [comment]
I've added to the ticket, could we specify exactly which flows we are creating? i.e., user flow for submittion emission report,  user flow for submitting compliance obligation, etc. registration for the first time, registering a facility, registering for BORO ID, etc. @suhafa

**Comment by suhafa** [comment]
Updated AC & task

**Comment by patriciarussellCAS** [comment]
Given Suha is away I've added this to Spring 9 as well.
