### ISSUE TITLE
SSL certificate

### ISSUE THREAD

**Issue by mikevespi** [bcgov/cas-reporting#87]
We will need to get our own SSL certificate for the reporting subdomain. Confirm the subdomain and domain name with the product owner, and follow the steps found in Teams 'Scrum Team' files, under OBPS > Domain setup. Alternatively, we could try again to get a certificate that covers all subdomains, which would save us from needing to do this again for all future modules, as well as reduce the effort of renewing in the future.

**Comment by mikevespi** [comment]
This isn't so much necessary for the Milestone, but the process can take a while so I've included it here to get the ball rolling early.

**Comment by pbastia** [comment]
@mikevespi do you know how hard it is to get a wildcard cert for subdomains? I know the gov has been very reticent with it in the past. 
I wonder if the BA or our PO has any opinion in that @patriciarussellCAS 
we can definitely starts the steps to procure a `registration.our_obps_domain.ca` URL

**Comment by mikevespi** [comment]
My understanding is that the process is similar but the cert itself is more expensive. After talking to Dylan briefly the other day, it sounds like we already have two certs paid for. One for the industrialemissions domain, and one for the `registration` subdomain. He mentioned that the cost of a wildcard is a little bit higher than the sum of the individual ones we'll need, so seeing as we already have two he was planning on following that pattern. If it's an option I'm on board for trying to get one with a wildcard to avoid going through this process a couple more times, and make the renewal easier on us.

**Comment by pbastia** [comment]
the stance with Platform Services is that individual certs are more secure, since they trace the individual communication all the way to the pod(s), which can be beneficial when trying to isolate weird network traffic. Wildcard certs allow you to encrypt communication spread out over multiple pods/namespaces

**Comment by pbastia** [comment]
closing as we'll use the same as the registration app
