### ISSUE TITLE
Create short 'what we heard' summary from ext. user research

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-reporting#9]
Now that we have conducted our research analysis, let's create a short summary of what we heard to pass back to the wider branch. We may have different groups.

Acceptance Criteria:
- [ ] Create artefact(s) with: themed findings, recommendations

Goal of ticket:
- Be able to share learnings with the branch
- Communicate the value of the research conducted

**Comment by NicoleGovvy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Giraffe-Sprint-Board-64597698d333490011486ab9/issues/bcgov/cas-reporting/9?planning-poker) with Zenhub @jaimiebutton @NicoleGovvy

**Comment by patriciarussellCAS** [comment]
@NicoleGovvy - do we want a separate card for the actual report out to the branch? (so this is prep and the other card is presentation?)
