### ISSUE TITLE
Save a snapshot of the repo after initialization to prepare for it's re-use on similar projects

### ISSUE THREAD

**Issue by joshgamache** [bcgov/cas-reporting#94]
**Dev Story**:
_I want_ a snapshot of the initialized repository
_because_ we will be spinning up a new repo soon with the same basic structure
_and this will help me to_ avoid redoing similar initialization again.

**Acceptance criteria**:

## Tasks

- [ ] Create a repository snapshot of `cas-reporting`

**Comment by pbastia** [comment]
Closing, this would be replaced by cas-reporting#1273
