### ISSUE TITLE
Initialize Helm Chart

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-reporting#95]
#### Describe the task

As a developer, 
I want to have access to a helm chart, 
So that I can deploy the reporting app on the OpenShift cluster

Helm templates currently used in registration: https://github.com/bcgov/cas-registration/tree/develop/helm/cas-registration

#### Acceptance Criteria

- [x] a Helm chart with both frontend and backend templates
- [x] said Helm chart can be deployed to the bcgov openshift cluster

**Comment by rdromey** [comment]
Moving to monorepo model, no longer necessary
